export const DISHES = {
  'chicken-rice': {
    id: 'chicken-rice',
    name: 'Chicken Rice',
    nameLocal: '鸡饭',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍚',
    color: '#F59E0B',
    bgColor: '#FEF3C7',
    description: 'Steamed or roasted chicken with fragrant rice cooked in chicken broth, served with chilli and ginger sauce.',
    baseCalories: 480,
    calorieRange: { min: 350, max: 750 },
    hiddenCalories: [
      'Chicken skin adds 50–80 kcal — easy to miss',
      'Rice cooked in chicken fat (oilier than plain rice)',
      'Chilli sauce: 20–40 kcal per tablespoon',
      'Ginger paste on the side adds ~20 kcal',
    ],
    macros: { protein: 28, carbs: 58, fat: 14, fiber: 1 },
    tags: ['Rice', 'Chicken', 'Classic'],
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: "Half portion / child's meal", icon: '🤏', modifier: -100 },
          { id: 'regular', label: 'Regular', desc: 'Standard hawker serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Extra rice added', icon: '👐', modifier: 130 },
          { id: 'xl', label: 'Double Rice', desc: 'Two scoops of rice', icon: '🙌', modifier: 220 },
        ],
      },
      {
        id: 'style',
        question: 'Which style of chicken?',
        subtitle: 'Different cooking methods change the calorie count',
        type: 'single',
        options: [
          { id: 'steamed', label: 'Steamed (Bai Qie)', desc: 'Lighter, poached in broth', icon: '💧', modifier: -30 },
          { id: 'roasted', label: 'Roasted (Shao Ji)', desc: 'Crispy skin, more flavour', icon: '🔥', modifier: 20 },
          { id: 'soy', label: 'Soy Sauce', desc: 'Braised in dark soy', icon: '🤎', modifier: 15 },
        ],
      },
      {
        id: 'extras',
        question: 'Any add-ons on your plate?',
        subtitle: 'Select all that apply',
        type: 'multi',
        options: [
          { id: 'egg', label: 'Soft-boiled egg', icon: '🥚', modifier: 70 },
          { id: 'char_siu', label: 'Char Siu slice', icon: '🥩', modifier: 110 },
          { id: 'extra_chicken', label: 'Extra chicken', icon: '🍗', modifier: 150 },
          { id: 'none', label: 'No add-ons', icon: '✓', modifier: 0, exclusive: true },
        ],
      },
    ],
  },

  'nasi-lemak': {
    id: 'nasi-lemak',
    name: 'Nasi Lemak',
    nameLocal: 'Nasi Lemak (MY)',
    origin: 'Malaysia',
    flag: '🇲🇾',
    emoji: '🍛',
    color: '#16A34A',
    bgColor: '#DCFCE7',
    description: 'Fragrant coconut rice served with crispy anchovies, roasted peanuts, boiled egg, cucumber and spicy sambal.',
    baseCalories: 620,
    calorieRange: { min: 440, max: 900 },
    hiddenCalories: [
      'Coconut rice is calorie-dense — more fat than plain rice',
      'Sambal chilli: 30–80 kcal depending on amount',
      'Fried chicken (if included) adds 150–200 kcal',
      'Crispy anchovies and peanuts are high in fat',
    ],
    macros: { protein: 20, carbs: 72, fat: 28, fiber: 4 },
    tags: ['Rice', 'Coconut', 'Spicy'],
    questions: [
      {
        id: 'protein',
        question: 'What protein came with it?',
        subtitle: 'Protein choice is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'egg', label: 'Boiled egg only', desc: 'Standard set', icon: '🥚', modifier: 0 },
          { id: 'fried_chicken', label: 'Fried chicken', desc: 'Classic add-on', icon: '🍗', modifier: 180 },
          { id: 'rendang', label: 'Beef rendang', desc: 'Rich dry curry', icon: '🥩', modifier: 130 },
          { id: 'none', label: 'No protein', desc: 'Veg/plain set', icon: '🌿', modifier: -80 },
        ],
      },
      {
        id: 'sambal',
        question: 'How much sambal?',
        subtitle: 'Sambal adds significant calories in large amounts',
        type: 'single',
        options: [
          { id: 'none', label: 'None', icon: '🚫', modifier: -30 },
          { id: 'light', label: 'Light', icon: '🔹', modifier: 0 },
          { id: 'normal', label: 'Normal', icon: '🌶️', modifier: 40 },
          { id: 'extra', label: 'Extra sambal', icon: '🔥', modifier: 90 },
        ],
      },
    ],
  },

  'char-kway-teow': {
    id: 'char-kway-teow',
    name: 'Char Kway Teow',
    nameLocal: '炒粿条',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🥘',
    color: '#92400E',
    bgColor: '#FEF3C7',
    description: 'Stir-fried flat rice noodles in a rich dark sauce with prawns, cockles, Chinese sausage, eggs and bean sprouts.',
    baseCalories: 680,
    calorieRange: { min: 450, max: 870 },
    hiddenCalories: [
      'Lard used in wok frying adds 60–100 kcal',
      'Dark soy sauce contains sugar',
      'Chinese sausage (lap cheong) is high in fat',
      'Cockles are low-cal but often missed in tracking',
    ],
    macros: { protein: 22, carbs: 78, fat: 32, fiber: 2 },
    tags: ['Noodles', 'Wok-fried', 'Seafood'],
    questions: [
      {
        id: 'portion',
        question: 'How big was the plate?',
        subtitle: 'Portion is the main driver of calories here',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light plate', icon: '🤏', modifier: -150 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Bigger serving', icon: '👐', modifier: 150 },
        ],
      },
      {
        id: 'lard',
        question: 'Was lard used in cooking?',
        subtitle: 'Lard is traditional but significantly increases calories',
        type: 'single',
        options: [
          { id: 'no', label: 'No lard', desc: 'Requested healthy', icon: '🥗', modifier: -80 },
          { id: 'yes', label: 'Standard lard', desc: 'Traditional cooking', icon: '🍳', modifier: 0 },
          { id: 'extra', label: 'Extra lard', desc: 'Very rich plate', icon: '🔥', modifier: 80 },
        ],
      },
    ],
  },

  'laksa': {
    id: 'laksa',
    name: 'Laksa',
    nameLocal: '叻沙',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍜',
    color: '#EA580C',
    bgColor: '#FFEDD5',
    description: 'Rich and spicy coconut milk noodle soup loaded with prawns, tofu puffs, cockles, and fresh laksa leaves.',
    baseCalories: 610,
    calorieRange: { min: 380, max: 760 },
    hiddenCalories: [
      'Coconut milk broth holds 100–200 kcal on its own',
      'Tofu puffs absorb oil — each puff adds ~40 kcal',
      'Laksa paste base is oil-heavy',
      'Cockles add minimal calories but are easy to forget',
    ],
    macros: { protein: 24, carbs: 68, fat: 28, fiber: 3 },
    tags: ['Noodles', 'Coconut', 'Spicy'],
    questions: [
      {
        id: 'broth',
        question: 'How much broth did you drink?',
        subtitle: 'The coconut broth holds most of the calories',
        type: 'single',
        options: [
          { id: 'none', label: 'Left it all', desc: 'Ate solids only', icon: '🚫', modifier: -160 },
          { id: 'little', label: 'A little sip', desc: 'Left most of it', icon: '💧', modifier: -80 },
          { id: 'half', label: 'About half', desc: 'Moderate amount', icon: '🌊', modifier: -40 },
          { id: 'all', label: 'Finished it', desc: 'Drank the whole bowl', icon: '🥣', modifier: 0 },
        ],
      },
      {
        id: 'portion',
        question: 'Bowl size?',
        subtitle: 'Portion affects noodles and toppings',
        type: 'single',
        options: [
          { id: 'small', label: 'Small bowl', icon: '🤏', modifier: -80 },
          { id: 'regular', label: 'Regular', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large bowl', icon: '👐', modifier: 100 },
        ],
      },
    ],
  },

  'cai-png': {
    id: 'cai-png',
    name: 'Cai Png (Economy Rice)',
    nameLocal: '菜饭',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍱',
    color: '#0891B2',
    bgColor: '#CFFAFE',
    description: 'Mix-and-match rice plate with a selection of dishes from a steam tray.',
    baseCalories: 520,
    calorieRange: { min: 300, max: 800 },
    hiddenCalories: [
      'Braised dishes sit in oil-rich sauces — absorbs into rice',
      'Each fried item adds 80–130 kcal',
      'Rice scoop size varies widely between stalls',
      'Gravy poured on rice adds 30–60 kcal',
    ],
    macros: { protein: 22, carbs: 65, fat: 18, fiber: 4 },
    tags: ['Rice', 'Mixed', 'Value'],
    questions: [
      {
        id: 'rice',
        question: 'How many scoops of rice?',
        subtitle: 'Each scoop is about 130 kcal',
        type: 'single',
        options: [
          { id: 'half', label: 'Half scoop', icon: '🤏', modifier: -130 },
          { id: 'one', label: '1 scoop', icon: '👌', modifier: 0 },
          { id: 'two', label: '2 scoops', icon: '👐', modifier: 130 },
          { id: 'three', label: '3 scoops', icon: '🙌', modifier: 260 },
        ],
      },
      {
        id: 'dishes',
        question: 'What type of dishes did you pick?',
        subtitle: 'Select all that apply',
        type: 'multi',
        options: [
          { id: 'veg', label: 'Stir-fried vegetables', icon: '🥦', modifier: -60 },
          { id: 'egg', label: 'Egg dish', icon: '🥚', modifier: 70 },
          { id: 'fried', label: 'A fried item', icon: '🍳', modifier: 120 },
          { id: 'braised', label: 'Braised meat', icon: '🥩', modifier: 100 },
        ],
      },
    ],
  },

  'pad-thai': {
    id: 'pad-thai',
    name: 'Pad Thai',
    nameLocal: 'ผัดไทย',
    origin: 'Thailand',
    flag: '🇹🇭',
    emoji: '🍜',
    color: '#CA8A04',
    bgColor: '#FEF9C3',
    description: 'Stir-fried rice noodles with eggs, tofu or shrimp, tamarind sauce, fish sauce, peanuts and bean sprouts.',
    baseCalories: 560,
    calorieRange: { min: 400, max: 750 },
    hiddenCalories: [
      'Peanuts add ~60 kcal per tablespoon — common to add extra',
      'Palm sugar in the sauce adds 30–50 kcal',
      'Wok oil is used generously in stir-frying',
      'Fried tofu absorbs more oil than fresh tofu',
    ],
    macros: { protein: 22, carbs: 68, fat: 24, fiber: 3 },
    tags: ['Noodles', 'Thai', 'Peanut'],
    questions: [
      {
        id: 'protein',
        question: 'Which protein?',
        subtitle: 'Protein choice affects calorie and fat content',
        type: 'single',
        options: [
          { id: 'tofu', label: 'Tofu only', desc: 'Lighter option', icon: '🟡', modifier: -60 },
          { id: 'shrimp', label: 'Shrimp', desc: 'Classic choice', icon: '🦐', modifier: 0 },
          { id: 'chicken', label: 'Chicken', icon: '🍗', modifier: 50 },
          { id: 'mix', label: 'Mixed', desc: 'Chicken + shrimp', icon: '🥘', modifier: 80 },
        ],
      },
      {
        id: 'portion',
        question: 'How big was the portion?',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', icon: '🤏', modifier: -100 },
          { id: 'regular', label: 'Regular', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', icon: '👐', modifier: 120 },
        ],
      },
    ],
  },

  'pho': {
    id: 'pho',
    name: 'Phở Bò',
    nameLocal: 'Phở bò',
    origin: 'Vietnam',
    flag: '🇻🇳',
    emoji: '🍲',
    color: '#065F46',
    bgColor: '#D1FAE5',
    description: 'Vietnamese slow-simmered beef bone broth with flat rice noodles, thin-sliced beef, fresh herbs and lime.',
    baseCalories: 480,
    calorieRange: { min: 320, max: 640 },
    hiddenCalories: [
      'Bone broth has beef fat from hours of simmering',
      'Hoisin and sriracha dipping sauces add 40–60 kcal',
      'Fatty brisket has significantly more fat than rare slices',
      'Finishing the broth adds 80–120 kcal',
    ],
    macros: { protein: 30, carbs: 58, fat: 12, fiber: 2 },
    tags: ['Soup', 'Beef', 'Vietnamese'],
    questions: [
      {
        id: 'broth',
        question: 'How much broth did you finish?',
        subtitle: 'Beef broth has fat from long simmering',
        type: 'single',
        options: [
          { id: 'little', label: 'Left most', desc: 'Just the solids', icon: '🚫', modifier: -100 },
          { id: 'half', label: 'About half', icon: '💧', modifier: -50 },
          { id: 'most', label: 'Almost all', icon: '🌊', modifier: -20 },
          { id: 'all', label: 'Finished it', icon: '🥣', modifier: 0 },
        ],
      },
      {
        id: 'beef',
        question: 'Which cut of beef?',
        subtitle: 'Fatty cuts add considerably more calories',
        type: 'single',
        options: [
          { id: 'lean', label: 'Thinly sliced rare beef', desc: 'Lean cut', icon: '🥩', modifier: 0 },
          { id: 'brisket', label: 'Fatty brisket (Gầu)', desc: 'Rich, well-marbled', icon: '🫕', modifier: 80 },
          { id: 'mixed', label: 'Mixed cuts', desc: 'Brisket + rare beef', icon: '🍖', modifier: 50 },
        ],
      },
    ],
  },

  'nasi-goreng': {
    id: 'nasi-goreng',
    name: 'Nasi Goreng',
    nameLocal: 'Nasi Goreng',
    origin: 'Indonesia',
    flag: '🇮🇩',
    emoji: '🍛',
    color: '#B45309',
    bgColor: '#FEF3C7',
    description: 'Indonesian fried rice seasoned with kecap manis, shrimp paste and chilli, topped with a fried egg and crackers.',
    baseCalories: 660,
    calorieRange: { min: 440, max: 870 },
    hiddenCalories: [
      'Kecap manis (sweet soy) adds sugar — 30–50 kcal',
      'Fried egg on top adds ~70 kcal',
      'Wok oil used generously in frying adds 60–100 kcal',
      'Prawn crackers on the side: ~80 kcal per small serving',
    ],
    macros: { protein: 22, carbs: 82, fat: 28, fiber: 2 },
    tags: ['Rice', 'Fried', 'Indonesian'],
    questions: [
      {
        id: 'egg',
        question: 'Fried egg on top?',
        subtitle: 'Classic nasi goreng includes a sunny-side egg',
        type: 'single',
        options: [
          { id: 'no', label: 'No egg', icon: '🚫', modifier: -70 },
          { id: 'yes', label: 'Yes, fried egg', icon: '🍳', modifier: 0 },
        ],
      },
      {
        id: 'portion',
        question: 'How much rice?',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', icon: '🤏', modifier: -150 },
          { id: 'regular', label: 'Regular', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', icon: '👐', modifier: 150 },
        ],
      },
    ],
  },

  'bubble-tea': {
    id: 'bubble-tea',
    name: 'Bubble Tea',
    nameLocal: '珍珠奶茶',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🧋',
    color: '#7C3AED',
    bgColor: '#EDE9FE',
    description: 'Milk tea or fruit tea with chewy tapioca pearls.',
    baseCalories: 330,
    calorieRange: { min: 120, max: 580 },
    hiddenCalories: [
      'Tapioca pearls: ~150 kcal per regular cup serving',
      'Full sugar vs no sugar = difference of ~100 kcal',
      'Coconut jelly or pudding toppings add 50–80 kcal',
      'Cheese foam topping adds ~80–120 kcal',
    ],
    macros: { protein: 3, carbs: 60, fat: 8, fiber: 0 },
    tags: ['Drink', 'Sweet', 'Tea'],
    questions: [
      {
        id: 'size',
        question: 'What size?',
        type: 'single',
        options: [
          { id: 'small', label: 'Medium (500ml)', icon: '🥤', modifier: -80 },
          { id: 'large', label: 'Large (700ml)', icon: '🧋', modifier: 80 },
        ],
      },
      {
        id: 'sugar',
        question: 'Sugar level?',
        subtitle: 'Sugar level has the biggest impact on calories',
        type: 'single',
        options: [
          { id: 'zero', label: '0%', desc: 'No sugar', icon: '🚫', modifier: -80 },
          { id: 'quarter', label: '25%', icon: '🔹', modifier: -40 },
          { id: 'half', label: '50%', desc: 'Default in some shops', icon: '🌓', modifier: 0 },
          { id: 'full', label: '100%', desc: 'Full sugar', icon: '🍬', modifier: 100 },
        ],
      },
      {
        id: 'toppings',
        question: 'Toppings?',
        subtitle: 'Pearls and extras add meaningful calories',
        type: 'single',
        options: [
          { id: 'none', label: 'No toppings', icon: '✓', modifier: -80 },
          { id: 'pearls', label: 'Tapioca pearls', desc: 'Classic boba', icon: '⚫', modifier: 0 },
          { id: 'jelly', label: 'Grass jelly', desc: 'Lower calorie option', icon: '🟫', modifier: -20 },
          { id: 'pudding', label: 'Egg pudding', icon: '🟡', modifier: 60 },
        ],
      },
    ],
  },

  'roti-prata': {
    id: 'roti-prata',
    name: 'Roti Prata',
    nameLocal: 'Roti Prata (SG)',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🫓',
    color: '#D97706',
    bgColor: '#FEF3C7',
    description: 'Crispy, flaky pan-fried flatbread cooked with ghee, served with fish or mutton curry for dipping.',
    baseCalories: 350,
    calorieRange: { min: 180, max: 580 },
    hiddenCalories: [
      'Ghee used in cooking adds 40–80 kcal per prata',
      'Curry dip adds 60–100 kcal depending on amount',
      'Egg prata has an extra 70–90 kcal per egg',
      'Sugar prata adds ~50 kcal vs plain',
    ],
    macros: { protein: 8, carbs: 44, fat: 17, fiber: 1 },
    tags: ['Bread', 'Indian', 'Fried'],
    questions: [
      {
        id: 'quantity',
        question: 'How many pratas?',
        type: 'single',
        options: [
          { id: 'one_plain', label: '1 plain prata', icon: '1️⃣', modifier: -100 },
          { id: 'two_plain', label: '2 plain pratas', desc: 'Standard order', icon: '2️⃣', modifier: 0 },
          { id: 'one_egg', label: '1 egg prata', icon: '🥚', modifier: -30 },
          { id: 'two_egg', label: '2 egg pratas', icon: '🍳', modifier: 110 },
        ],
      },
      {
        id: 'curry',
        question: 'How much curry dip?',
        subtitle: 'Curry sauce is calorie-dense',
        type: 'single',
        options: [
          { id: 'none', label: 'None', icon: '🚫', modifier: -60 },
          { id: 'light', label: 'Light dip', icon: '🔹', modifier: 0 },
          { id: 'normal', label: 'Normal dip', icon: '🍛', modifier: 60 },
          { id: 'lots', label: 'Extra curry', icon: '🔥', modifier: 130 },
        ],
      },
    ],
  },

  'hokkien-mee': {
    id: 'hokkien-mee',
    name: 'Hokkien Mee',
    nameLocal: '福建炒面',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍝',
    color: '#C2410C',
    bgColor: '#FFEDD5',
    description: 'Braised yellow noodles and thin rice noodles with prawns, squid, pork belly slices and egg.',
    baseCalories: 580,
    calorieRange: { min: 400, max: 780 },
    hiddenCalories: [
      'Lard drizzled on top at serving: 60–80 kcal',
      'Prawn stock base has natural fat',
      'Pork belly pieces are high in fat',
      'Sambal chilli on the side adds 20–40 kcal',
    ],
    macros: { protein: 26, carbs: 70, fat: 20, fiber: 2 },
    tags: ['Noodles', 'Seafood', 'Braised'],
    questions: [
      {
        id: 'portion',
        question: 'Portion size?',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', icon: '🤏', modifier: -120 },
          { id: 'regular', label: 'Regular', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', icon: '👐', modifier: 120 },
        ],
      },
      {
        id: 'lard',
        question: 'Lard drizzled on top?',
        subtitle: 'Traditional Hokkien Mee often includes lard at serving',
        type: 'single',
        options: [
          { id: 'no', label: 'No lard', desc: 'Requested without', icon: '🥗', modifier: -70 },
          { id: 'yes', label: 'With lard', desc: 'Traditional style', icon: '🍳', modifier: 0 },
        ],
      },
    ],
  },

  'satay': {
    id: 'satay',
    name: 'Satay',
    nameLocal: 'สะเต๊ะ',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍢',
    color: '#78350F',
    bgColor: '#FEF3C7',
    description: 'Grilled marinated meat skewers served with peanut sauce, ketupat and fresh cucumber slices.',
    baseCalories: 400,
    calorieRange: { min: 200, max: 680 },
    hiddenCalories: [
      'Peanut sauce: ~80 kcal per 2 tbsp serving',
      'Marinades contain palm sugar — adds 20–40 kcal',
      'Beef and mutton skewers have more fat than chicken',
      'Ketupat (rice cake) on the side adds ~80 kcal',
    ],
    macros: { protein: 32, carbs: 24, fat: 18, fiber: 2 },
    tags: ['Grilled', 'Skewer', 'Peanut'],
    questions: [
      {
        id: 'sticks',
        question: 'How many sticks?',
        subtitle: 'The base estimate is for 5 sticks',
        type: 'single',
        options: [
          { id: 'three', label: '3 sticks', icon: '3️⃣', modifier: -160 },
          { id: 'five', label: '5 sticks', desc: 'Base estimate', icon: '5️⃣', modifier: 0 },
          { id: 'eight', label: '8 sticks', icon: '8️⃣', modifier: 160 },
          { id: 'ten', label: '10 sticks', icon: '🔟', modifier: 280 },
        ],
      },
      {
        id: 'sauce',
        question: 'Peanut sauce amount?',
        subtitle: 'Peanut sauce is rich in calories and fat',
        type: 'single',
        options: [
          { id: 'none', label: 'None', icon: '🚫', modifier: -60 },
          { id: 'light', label: 'Light', icon: '🔹', modifier: -20 },
          { id: 'normal', label: 'Normal', icon: '🥜', modifier: 0 },
          { id: 'extra', label: 'Extra sauce', icon: '🔥', modifier: 80 },
        ],
      },
    ],
  },
}

export const FEATURED_DISH_IDS = [
  'chicken-rice', 'nasi-lemak', 'char-kway-teow', 'laksa', 'cai-png', 'pad-thai',
  'pho', 'nasi-goreng', 'bubble-tea', 'roti-prata', 'hokkien-mee', 'satay',
]

export const MEAL_TYPES = [
  { id: 'breakfast', label: 'Breakfast', icon: '🌅', time: '6–11am' },
  { id: 'lunch', label: 'Lunch', icon: '☀️', time: '11am–3pm' },
  { id: 'dinner', label: 'Dinner', icon: '🌙', time: '3–10pm' },
  { id: 'snack', label: 'Snack', icon: '🍵', time: 'Anytime' },
]

export function getMealForTime() {
  const h = new Date().getHours()
  if (h >= 6 && h < 11) return 'breakfast'
  if (h >= 11 && h < 15) return 'lunch'
  if (h >= 15 && h < 22) return 'dinner'
  return 'snack'
}

export function mockDetect() {
  const id = FEATURED_DISH_IDS[Math.floor(Math.random() * FEATURED_DISH_IDS.length)]
  return {
    dishId: id,
    confidence: Math.round((0.76 + Math.random() * 0.21) * 100),
  }
}
