  'kopi-o': {
    id: 'kopi-o',
    name: 'Kopi O',
    nameLocal: 'Kopi O',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '☕',
    color: '#2563EB',
    bgColor: '#DBEAFE',
    description: 'Strong black Robusta coffee sweetened with sugar only — no milk — served in a small ceramic kopitiam cup with a dark, near-black brew.',
    baseCalories: 30,
    calorieRange: { min: 15, max: 55 },
    macros: { protein: 0, carbs: 7, fat: 0, fiber: 0 },
    tags: ['Drink', 'Coffee', 'Kopitiam', 'Hot'],
    visual_detection: {
      protein: 'none',
      starch: 'none',
      sauce: 'dark brown to black liquid, no milk swirl, no creaminess, surface is uniformly dark',
      sides: 'none',
      plating: 'small white ceramic kopitiam cup and saucer, typically 150–180 ml',
      key_identifiers: [
        'Very dark brown to black liquid — no milk of any kind',
        'Small ceramic kopitiam cup and saucer (not a tall glass)',
        'No white or cream swirl on surface',
        'Uniform dark colour from rim to centre',
        'Strong roasted Robusta coffee aroma',
      ],
      common_lookalikes: ['Kopi', 'Kopi C', 'Teh O'],
      differentiators: 'Dark brown/black liquid with NO white milk swirl distinguishes from Kopi (condensed milk) and Kopi C (evaporated milk); darker colour than Teh O which is amber/golden; same small ceramic kopitiam cup as all kopitiam drinks.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -10 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 15 },
        ],
      },
    ],
  },

  'kopi-c': {
    id: 'kopi-c',
    name: 'Kopi C',
    nameLocal: 'Kopi C',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '☕',
    color: '#2563EB',
    bgColor: '#DBEAFE',
    description: 'Kopitiam Robusta coffee with unsweetened evaporated milk and sugar, producing a lighter medium-brown colour and a thinner, less sweet taste than condensed milk kopi.',
    baseCalories: 80,
    calorieRange: { min: 55, max: 120 },
    macros: { protein: 3, carbs: 12, fat: 2, fiber: 0 },
    tags: ['Drink', 'Coffee', 'Kopitiam', 'Hot'],
    visual_detection: {
      protein: 'none',
      starch: 'none',
      sauce: 'medium brown liquid — lighter than kopi O, not as pale or creamy as condensed milk kopi; thin evaporated milk gives a uniform warm brown',
      sides: 'none',
      plating: 'small white ceramic kopitiam cup and saucer, 150–180 ml',
      key_identifiers: [
        'Medium warm brown colour — not dark black like kopi O',
        'No thick cream or condensed milk layering at bottom',
        'Uniform medium-brown colour throughout (evaporated milk blends fully)',
        'Small ceramic kopitiam cup and saucer',
        'Lighter, less viscous appearance than condensed milk kopi',
      ],
      common_lookalikes: ['Kopi', 'Kopi O', 'Teh C'],
      differentiators: 'Medium brown from evaporated milk (thinner than the pale caramel of condensed milk kopi); darker than Teh C which is golden-brown tea; no dark near-black colour like Kopi O; served in same small ceramic kopitiam cup.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -16 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 20 },
        ],
      },
    ],
  },

  'teh-o': {
    id: 'teh-o',
    name: 'Teh O',
    nameLocal: 'Teh O',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍵',
    color: '#2563EB',
    bgColor: '#DBEAFE',
    description: 'Kopitiam black tea sweetened with sugar only, producing a clear amber to golden liquid with no milk, served in a small ceramic cup.',
    baseCalories: 25,
    calorieRange: { min: 15, max: 45 },
    macros: { protein: 0, carbs: 6, fat: 0, fiber: 0 },
    tags: ['Drink', 'Tea', 'Kopitiam', 'Hot'],
    visual_detection: {
      protein: 'none',
      starch: 'none',
      sauce: 'clear amber to golden-orange liquid, transparent and bright, no opacity from milk',
      sides: 'none',
      plating: 'small white ceramic kopitiam cup and saucer, 150–180 ml',
      key_identifiers: [
        'Clear amber/golden-orange colour — visibly translucent, not opaque',
        'No milk, no white swirl — transparent liquid',
        'Small ceramic kopitiam cup and saucer',
        'Lighter and more golden in hue than dark Kopi O',
        'Clean tea aroma, not coffee',
      ],
      common_lookalikes: ['Kopi O', 'Teh', 'Teh C'],
      differentiators: 'Amber/golden clear colour distinguishes from dark brown Kopi O; no milk unlike Teh (condensed milk) and Teh C (evaporated milk) which are opaque; lighter golden hue vs darker brown of Teh C.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -10 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 15 },
        ],
      },
    ],
  },

  'teh-c': {
    id: 'teh-c',
    name: 'Teh C',
    nameLocal: 'Teh C',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍵',
    color: '#2563EB',
    bgColor: '#DBEAFE',
    description: 'Kopitiam black tea with unsweetened evaporated milk and sugar, producing a smooth medium golden-brown drink served in a small ceramic cup.',
    baseCalories: 75,
    calorieRange: { min: 50, max: 110 },
    macros: { protein: 3, carbs: 11, fat: 2, fiber: 0 },
    tags: ['Drink', 'Tea', 'Kopitiam', 'Hot'],
    visual_detection: {
      protein: 'none',
      starch: 'none',
      sauce: 'medium golden-brown opaque liquid — evaporated milk gives a warm honey-brown tint, lighter and more golden than coffee-based Kopi C',
      sides: 'none',
      plating: 'small white ceramic kopitiam cup and saucer, 150–180 ml',
      key_identifiers: [
        'Medium golden-brown colour — warmer and more golden than Kopi C which is darker',
        'Slight opacity from evaporated milk but not as pale or thick as condensed milk teh',
        'Small ceramic kopitiam cup and saucer',
        'Tea aroma (not coffee)',
        'Uniform colour throughout — evaporated milk blends without layering',
      ],
      common_lookalikes: ['Teh', 'Teh O', 'Kopi C'],
      differentiators: 'Golden-brown tea colour (not dark coffee brown of Kopi C); more opaque than clear Teh O; lighter and less sweet than condensed milk Teh; same small ceramic cup as all kopitiam drinks.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -15 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 19 },
        ],
      },
    ],
  },

  'barley-water': {
    id: 'barley-water',
    name: 'Barley Water',
    nameLocal: 'Barley Water / Yi Mi Shui',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🥤',
    color: '#2563EB',
    bgColor: '#DBEAFE',
    description: 'Sweetened Chinese barley drink with a cloudy pale yellow-white appearance, whole pearl barley grains settled at the bottom, served chilled or warm.',
    baseCalories: 120,
    calorieRange: { min: 80, max: 180 },
    macros: { protein: 2, carbs: 28, fat: 0, fiber: 1 },
    tags: ['Drink', 'Chinese', 'Chilled', 'Herbal'],
    visual_detection: {
      protein: 'none',
      starch: 'whole pearl barley grains visible at the bottom of the cup',
      sauce: 'cloudy to milky pale yellow-white sweetened liquid — not transparent, not pure white',
      sides: 'none',
      plating: 'plastic cup or clear glass, 250–400 ml, whole barley grains visible settling at bottom',
      key_identifiers: [
        'Cloudy pale yellow-white liquid — not clear like chrysanthemum tea',
        'Whole pearl barley grains visible sinking to bottom of cup',
        'Served in plastic cup or clear glass (not ceramic kopitiam cup)',
        'Mild slightly starchy sweetness, not floral',
        'Grains clearly distinguish it from all other drinks',
      ],
      common_lookalikes: ['Chrysanthemum Tea', 'Soya Bean Milk', 'Sugar Cane Juice'],
      differentiators: 'Whole grain barley grains at bottom are uniquely identifying; cloudier and more yellow-tinted than pure white soya bean milk; no flowers floating unlike chrysanthemum tea; not as clear or golden as chrysanthemum tea.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -24 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 30 },
        ],
      },
    ],
  },

  'chrysanthemum-tea': {
    id: 'chrysanthemum-tea',
    name: 'Chrysanthemum Tea',
    nameLocal: '菊花茶',
    origin: 'China',
    flag: '🇨🇳',
    emoji: '🌼',
    color: '#2563EB',
    bgColor: '#DBEAFE',
    description: 'Lightly sweetened floral herbal tea brewed from dried chrysanthemum flowers, producing a clear pale golden-yellow liquid with visible whole dried flower petals.',
    baseCalories: 40,
    calorieRange: { min: 20, max: 70 },
    macros: { protein: 0, carbs: 10, fat: 0, fiber: 0 },
    tags: ['Drink', 'Chinese', 'Herbal', 'Floral'],
    visual_detection: {
      protein: 'none',
      starch: 'none',
      sauce: 'clear to pale golden-yellow floral liquid — transparent and light, much clearer than barley water',
      sides: 'whole dried chrysanthemum flower petals floating or settled in the liquid',
      plating: 'clear glass or plastic cup, 250–400 ml, flowers visible through the transparent liquid',
      key_identifiers: [
        'Clear pale golden-yellow colour — transparent and bright',
        'Whole dried chrysanthemum flower petals visibly floating in the liquid',
        'Delicate floral aroma',
        'No grains, no cloudiness unlike barley water',
        'Served in clear cup to display the flowers',
      ],
      common_lookalikes: ['Barley Water', 'Teh O', 'Sugar Cane Juice'],
      differentiators: 'Yellow floral tea with whole dried flower petals floating is uniquely identifying; clear transparent liquid (not cloudy like barley water); more golden and floral compared to amber tea colour of Teh O; flowers are the definitive visual marker.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -10 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 15 },
        ],
      },
    ],
  },

  'soya-bean-milk': {
    id: 'soya-bean-milk',
    name: 'Soya Bean Milk',
    nameLocal: '豆浆 Dou Jiang',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🥛',
    color: '#2563EB',
    bgColor: '#DBEAFE',
    description: 'Fresh creamy white soy milk made from ground soybeans, lightly sweetened, sometimes served warm or cold in a plastic bag with a straw or a glass.',
    baseCalories: 130,
    calorieRange: { min: 80, max: 200 },
    macros: { protein: 6, carbs: 14, fat: 4, fiber: 0 },
    tags: ['Drink', 'Chinese', 'Vegan', 'Soy'],
    visual_detection: {
      protein: 'none',
      starch: 'none',
      sauce: 'opaque pure white liquid — bright and uniform white throughout, no yellow tint unlike barley water',
      sides: 'sometimes tau huay (tofu pudding) added as a floating white lump',
      plating: 'transparent plastic bag with straw (hawker style), or glass/plastic cup 250–400 ml',
      key_identifiers: [
        'Opaque pure white colour — brighter white than coconut water or barley water',
        'Often served in transparent plastic bag with straw — iconic hawker presentation',
        'Fresh beany soy aroma',
        'No grains or flowers visible in the liquid',
        'Sometimes has a small scoop of tau huay (silken tofu pudding) floating',
      ],
      common_lookalikes: ['Barley Water', 'Coconut Milk', 'Fresh Milk'],
      differentiators: 'Opaque pure white (not pale yellow like barley water, not clear like coconut water); plastic bag serving is highly distinctive; fresh soy bean aroma; tau huay addition confirms identity.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -26 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 33 },
        ],
      },
    ],
  },

  'coconut-water': {
    id: 'coconut-water',
    name: 'Coconut Water',
    nameLocal: '',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🥥',
    color: '#2563EB',
    bgColor: '#DBEAFE',
    description: 'Natural electrolyte-rich liquid from a young green coconut, mildly sweet and refreshing, often served directly in the whole coconut with a straw.',
    baseCalories: 45,
    calorieRange: { min: 30, max: 70 },
    macros: { protein: 0, carbs: 11, fat: 0, fiber: 0 },
    tags: ['Drink', 'Natural', 'Chilled', 'Tropical'],
    visual_detection: {
      protein: 'none',
      starch: 'none',
      sauce: 'very pale, almost clear liquid — slightly opaque to transparent, with a very faint yellowish tint',
      sides: 'young coconut flesh (soft, translucent white jelly) scraped out and sometimes added to the drink',
      plating: 'whole green young coconut with top cut off and straw inserted, or clear glass/cup with ice',
      key_identifiers: [
        'Served in whole green coconut shell — the most distinctive presentation',
        'Very pale clear to slightly opaque liquid (not pure white like soya milk)',
        'Green coconut exterior visible if whole coconut presentation',
        'Soft translucent coconut jelly flesh sometimes visible in glass',
        'Natural subtle sweetness with no strong colour',
      ],
      common_lookalikes: ['Soya Bean Milk', 'Sugar Cane Juice', 'Barley Water'],
      differentiators: 'Whole green coconut serving vessel is unmistakable; clear to very pale liquid (much clearer than soya bean milk); no grains or flowers; green coconut shell is the definitive identifier.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -10 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 15 },
        ],
      },
    ],
  },

  'calamansi-juice': {
    id: 'calamansi-juice',
    name: 'Calamansi Juice',
    nameLocal: 'Calamansi Lime Juice',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍋',
    color: '#2563EB',
    bgColor: '#DBEAFE',
    description: 'Fresh-squeezed bright yellow-green citrus juice from small calamansi limes, tart and fragrant, served over ice with squeezed lime halves visible in the glass.',
    baseCalories: 80,
    calorieRange: { min: 50, max: 130 },
    macros: { protein: 0, carbs: 20, fat: 0, fiber: 0 },
    tags: ['Drink', 'Citrus', 'Fresh', 'Chilled'],
    visual_detection: {
      protein: 'none',
      starch: 'none',
      sauce: 'bright yellow-green to pale green liquid — vibrant citrus colour, slightly cloudy from fresh juice',
      sides: 'squeezed calamansi lime halves (small, 2–3 cm diameter) floating or visible in the glass',
      plating: 'tall glass or cup with ice cubes, 250–350 ml, lime halves visible',
      key_identifiers: [
        'Bright yellow-green colour — more vivid than lemon juice, greener than orange juice',
        'Small squeezed calamansi lime halves floating in the drink',
        'Served over ice in a tall glass',
        'Intense citrus aroma — more fragrant than regular lime juice',
        'Slightly cloudy from fresh-squeezed pulp',
      ],
      common_lookalikes: ['Lime Juice', 'Lemon Juice', 'Green Apple Juice'],
      differentiators: 'Small calamansi lime halves floating in glass are the key identifier; more intensely yellow-green than regular lime juice; smaller fruit halves than regular lime; served over ice in tall glass.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -16 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 20 },
        ],
      },
    ],
  },

  'watermelon-juice': {
    id: 'watermelon-juice',
    name: 'Watermelon Juice',
    nameLocal: '',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍉',
    color: '#2563EB',
    bgColor: '#DBEAFE',
    description: 'Fresh-blended bright pink-red watermelon juice, refreshingly sweet and hydrating, sometimes served with small watermelon chunks and ice.',
    baseCalories: 90,
    calorieRange: { min: 60, max: 140 },
    macros: { protein: 1, carbs: 22, fat: 0, fiber: 0 },
    tags: ['Drink', 'Fruit', 'Fresh', 'Chilled'],
    visual_detection: {
      protein: 'none',
      starch: 'none',
      sauce: 'bright pink to vivid red liquid — vibrant watermelon-pink colour, slightly opaque',
      sides: 'sometimes small watermelon chunks or seeds visible in the glass',
      plating: 'tall glass or plastic cup with ice, 300–400 ml, vivid pink-red colour throughout',
      key_identifiers: [
        'Distinctive bright pink to vivid red colour — unmistakably watermelon',
        'Slightly opaque, not as clear as sugar cane juice',
        'Served over ice in tall glass',
        'Refreshingly light texture despite vivid colour',
        'Sometimes small watermelon flesh pieces floating',
      ],
      common_lookalikes: ['Strawberry Juice', 'Roselle Juice', 'Pink Guava Juice'],
      differentiators: 'Bright watermelon-pink (slightly more orange-red than strawberry pink); lighter and more translucent than thick strawberry or guava juice; watermelon chunks if present confirm identity.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -18 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 23 },
        ],
      },
    ],
  },

  'tau-huay': {
    id: 'tau-huay',
    name: 'Tau Huay',
    nameLocal: '豆腐花 / Tau Huay',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '⬜',
    color: '#EC4899',
    bgColor: '#FCE7F3',
    description: 'Silken soft tofu pudding with an extremely smooth and delicate texture, served in clear ginger-infused or plain sugar syrup, eaten hot or cold.',
    baseCalories: 120,
    calorieRange: { min: 80, max: 180 },
    macros: { protein: 6, carbs: 18, fat: 3, fiber: 0 },
    tags: ['Dessert', 'Chinese', 'Tofu', 'Soft'],
    visual_detection: {
      protein: 'none',
      starch: 'none',
      sauce: 'clear pale golden ginger syrup or plain clear sugar syrup pooled around and over the tofu',
      sides: 'none — very minimalist presentation',
      plating: 'bowl or deep cup, smooth white tofu mounds scooped or ladled in, clear syrup surrounding',
      key_identifiers: [
        'Pure white, extremely smooth and quivering silken tofu — more delicate than firm tofu',
        'Clear syrup (not thick, not broth-like) surrounding the tofu',
        'Uniform pure white colour with no toppings or garnish',
        'Scooped into soft rounded mounds or ladled in pieces',
        'Served in a bowl — no competing colours or textures',
      ],
      common_lookalikes: ['Plain Congee', 'White Pudding', 'Almond Tofu'],
      differentiators: 'Pure white silken tofu texture is more delicate and wobblier than congee (which has rice grains); clear sugar or ginger syrup (not savoury broth); no rice visible unlike congee; texture smoother and more fragile than panna cotta or almond tofu.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -24 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 30 },
        ],
      },
    ],
  },

  'grass-jelly-cincau': {
    id: 'grass-jelly-cincau',
    name: 'Grass Jelly',
    nameLocal: '仙草 / Cincau / Chin Chow',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '⬛',
    color: '#EC4899',
    bgColor: '#FCE7F3',
    description: 'Jet-black grass jelly (xian cao) cubes with a slightly bitter herbal flavour, served in clear sugar syrup over ice or as a cold drink with syrup.',
    baseCalories: 100,
    calorieRange: { min: 65, max: 160 },
    macros: { protein: 1, carbs: 24, fat: 0, fiber: 1 },
    tags: ['Dessert', 'Chinese', 'Jelly', 'Herbal'],
    visual_detection: {
      protein: 'none',
      starch: 'none',
      sauce: 'clear sugar syrup or light brown sugar syrup pooled around the jelly cubes',
      sides: 'ice cubes if served cold',
      plating: 'bowl or tall cup, jet-black rectangular jelly cubes arranged or loosely placed, syrup surrounding',
      key_identifiers: [
        'Jet-black colour — distinctive and unmistakable, not dark brown or navy',
        'Cut into uniform rectangular or cube shapes',
        'Slightly wobbly jelly texture — not hard candy or chocolate',
        'Clear or light brown sugar syrup (not milk-based)',
        'Subtle herbal bitterness (visual clue: very dark, almost matte black surface)',
      ],
      common_lookalikes: ['Chocolate Jelly', 'Agar Agar (black)', 'Nata de Coco'],
      differentiators: 'Distinctive jet-black colour (not chocolate brown, not translucent dark); herbal origin distinguishes from flavoured agar; cube or rectangular shape is standard; served in sugar syrup not milk; slightly bitter taste not sweet like chocolate jelly.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -20 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 25 },
        ],
      },
    ],
  },

  'red-bean-soup': {
    id: 'red-bean-soup',
    name: 'Red Bean Soup',
    nameLocal: '红豆汤 Hong Dou Tang',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍮',
    color: '#EC4899',
    bgColor: '#FCE7F3',
    description: 'Warm sweet Chinese dessert soup of soft whole adzuki red beans in a lightly thickened reddish-brown broth, often with small sago pearls or lotus seeds.',
    baseCalories: 200,
    calorieRange: { min: 130, max: 290 },
    macros: { protein: 6, carbs: 40, fat: 1, fiber: 5 },
    tags: ['Dessert', 'Chinese', 'Soup', 'Bean'],
    visual_detection: {
      protein: 'none',
      starch: 'whole soft adzuki red beans throughout the broth; small translucent sago pearls sometimes visible',
      sauce: 'reddish-brown sweet broth — thin but lightly coloured from the beans, not opaque',
      sides: 'occasionally pandan leaves for aroma',
      plating: 'bowl or deep cup, served warm (or cold with ice), whole red beans and sago pearls visible throughout',
      key_identifiers: [
        'Whole dark red adzuki beans throughout — distinctive round legumes',
        'Reddish-brown sweet broth (not white or cream coloured)',
        'Translucent white sago pearls often mixed in',
        'Thin, broth-like consistency (not thick like red bean paste)',
        'Served in a bowl as a soup dessert',
      ],
      common_lookalikes: ['Peanut Soup', 'Green Bean Soup', 'Red Bean Ice'],
      differentiators: 'Dark red adzuki beans are visually distinctive from pale peanuts (peanut soup) or green beans; reddish-brown broth colour vs pale white of peanut soup; thinner consistency than red bean paste desserts.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -40 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 50 },
        ],
      },
    ],
  },

  'peanut-soup': {
    id: 'peanut-soup',
    name: 'Peanut Soup',
    nameLocal: '花生汤 Hua Sheng Tang',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🥣',
    color: '#EC4899',
    bgColor: '#FCE7F3',
    description: 'Warm sweet Chinese dessert soup with whole soft-boiled peanuts in a creamy pale beige broth that turns thick and nutty from long simmering.',
    baseCalories: 280,
    calorieRange: { min: 180, max: 400 },
    macros: { protein: 10, carbs: 28, fat: 14, fiber: 3 },
    tags: ['Dessert', 'Chinese', 'Soup', 'Peanut'],
    visual_detection: {
      protein: 'none',
      starch: 'whole soft-boiled peanuts (light beige, swollen, softened) throughout',
      sauce: 'creamy pale beige to milky white broth — thicker and more opaque than red bean soup broth, from peanut starch',
      sides: 'none',
      plating: 'bowl or deep cup, served warm, pale beige broth with whole swollen peanuts throughout',
      key_identifiers: [
        'Pale beige to off-white creamy broth — distinctly lighter colour than red bean soup',
        'Whole soft peanuts (without shells, inner skin may be pinkish) throughout',
        'Thick, milky, creamy consistency from peanut starch',
        'Nutty sweet aroma',
        'No red or dark coloured ingredients',
      ],
      common_lookalikes: ['Red Bean Soup', 'Almond Paste Soup', 'Green Bean Soup'],
      differentiators: 'Pale beige/white creamy broth (not reddish-brown like red bean soup); whole peanut legumes are distinctive; thicker consistency than green bean soup; nutty aroma distinguishes from almond paste which is smoother.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -56 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 70 },
        ],
      },
    ],
  },

  'bubur-cha-cha': {
    id: 'bubur-cha-cha',
    name: 'Bubur Cha Cha',
    nameLocal: 'Bubur Cha Cha',
    origin: 'Malaysia',
    flag: '🇲🇾',
    emoji: '🍡',
    color: '#EC4899',
    bgColor: '#FCE7F3',
    description: 'Peranakan coconut milk dessert soup with colourful cubes of taro (purple yam) and orange sweet potato, sago pearls, and pandan-scented sweetened coconut milk base.',
    baseCalories: 320,
    calorieRange: { min: 210, max: 450 },
    macros: { protein: 3, carbs: 52, fat: 12, fiber: 3 },
    tags: ['Dessert', 'Peranakan', 'Coconut', 'Colourful'],
    visual_detection: {
      protein: 'none',
      starch: 'cubed purple yam (taro), orange sweet potato, and small translucent sago pearls',
      sauce: 'white to slightly opaque creamy coconut milk base — pandan-scented, lightly sweetened',
      sides: 'pandan leaf sometimes visible in the bowl',
      plating: 'bowl or deep cup, served warm or cold with ice, colourful cubes prominent against white coconut milk',
      key_identifiers: [
        'Colourful purple (taro/yam) and orange (sweet potato) cubes in white coconut milk — very visually distinctive',
        'Translucent white sago pearls mixed throughout',
        'White coconut milk base — creamy, not broth-like',
        'Pandan fragrance',
        'Multi-coloured ingredient profile unlike any other dessert soup',
      ],
      common_lookalikes: ['Chendol', 'Red Bean Soup with Coconut', 'Tong Sui'],
      differentiators: 'Colourful purple yam and orange sweet potato cubes in white coconut milk are uniquely identifying; sago pearls add texture; no green pandan jelly strips unlike chendol; white coconut milk base (not clear syrup like other tong sui).',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -64 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 80 },
        ],
      },
    ],
  },

  'durian-pengat': {
    id: 'durian-pengat',
    name: 'Durian Pengat',
    nameLocal: '',
    origin: 'Malaysia',
    flag: '🇲🇾',
    emoji: '🍮',
    color: '#EC4899',
    bgColor: '#FCE7F3',
    description: 'Rich Peranakan dessert of ripe durian flesh simmered in thick coconut milk and palm sugar (gula melaka), creating a deeply fragrant, custard-like golden sauce.',
    baseCalories: 380,
    calorieRange: { min: 250, max: 530 },
    macros: { protein: 4, carbs: 38, fat: 22, fiber: 3 },
    tags: ['Dessert', 'Peranakan', 'Durian', 'Coconut'],
    visual_detection: {
      protein: 'none',
      starch: 'none — sometimes served with glutinous rice on the side',
      sauce: 'very thick golden-yellow to amber coconut milk and palm sugar sauce — custard-like consistency, much thicker than bubur cha cha',
      sides: 'sometimes served alongside glutinous rice or sago',
      plating: 'bowl or deep dish, pieces of yellow durian flesh sitting in or partially submerged in thick golden sauce',
      key_identifiers: [
        'Distinctive yellow durian flesh pieces — fibrous, creamy, unmistakable colour and form',
        'Very thick golden-amber sauce from coconut milk and palm sugar reduction',
        'Intensely strong durian aroma — the most pungent dessert smell',
        'Custard-like sauce consistency (not watery or broth-like)',
        'No other colourful vegetables or ingredients — pure durian and sauce',
      ],
      common_lookalikes: ['Mango Sticky Rice Sauce', 'Coconut Custard', 'Durian Ice Cream'],
      differentiators: 'Distinctive yellow durian flesh (thorny pod interior, fibrous texture) is unmistakable; intense durian smell is unique; thick golden sauce from palm sugar is darker than plain coconut desserts; no rice visible unlike mango sticky rice.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -76 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 95 },
        ],
      },
    ],
  },

  'kueh-lapis': {
    id: 'kueh-lapis',
    name: 'Kueh Lapis',
    nameLocal: '九层糕 / Kueh Lapis',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍰',
    color: '#EC4899',
    bgColor: '#FCE7F3',
    description: 'Steamed layered kueh with alternating coloured layers of pink, green, and white rice flour, cut into slices to reveal the distinct horizontal strata.',
    baseCalories: 140,
    calorieRange: { min: 95, max: 210 },
    macros: { protein: 2, carbs: 30, fat: 3, fiber: 0 },
    tags: ['Dessert', 'Kueh', 'Peranakan', 'Steamed'],
    visual_detection: {
      protein: 'none',
      starch: 'steamed rice flour and coconut milk layers, firm but slightly bouncy texture',
      sauce: 'none',
      sides: 'none',
      plating: 'slice on a plate or tray, showing clear horizontal coloured layers when viewed from the side',
      key_identifiers: [
        'Clear distinct alternating horizontal layers — typically pink, white, and green or pandan-coloured',
        'Each layer is thin and uniform, stacked 7–9 layers high',
        'Cut surface shows the layering dramatically',
        'Slightly translucent, gelatinous texture from rice flour',
        'Sold in rectangular slice form, not round like cake',
      ],
      common_lookalikes: ['Ang Ku Kueh', 'Rainbow Cake', 'Agar Agar Layered'],
      differentiators: 'Distinct horizontal colour layers visible from the side cut are uniquely identifying; rice flour steamed texture (not baked cake); thin uniform layers (not marbled or swirled); no red tortoise shell pattern unlike ang ku kueh.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -28 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 35 },
        ],
      },
    ],
  },

  'angku-kueh': {
    id: 'angku-kueh',
    name: 'Ang Ku Kueh',
    nameLocal: '红龟粿 Ang Ku Kueh',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🟠',
    color: '#EC4899',
    bgColor: '#FCE7F3',
    description: 'Traditional Hokkien red-orange oval glutinous rice kueh shaped like a tortoise shell with an embossed decorative pattern, filled with sweet peanut or mung bean paste, placed on a banana leaf square.',
    baseCalories: 130,
    calorieRange: { min: 85, max: 190 },
    macros: { protein: 3, carbs: 26, fat: 3, fiber: 1 },
    tags: ['Dessert', 'Kueh', 'Hokkien', 'Traditional'],
    visual_detection: {
      protein: 'none',
      starch: 'glutinous rice flour skin, chewy and slightly sticky, deep red-orange exterior',
      sauce: 'none',
      sides: 'small square of banana leaf underneath each piece',
      plating: 'individual oval/round pieces on banana leaf squares, displayed at room temperature on trays at hawker stalls',
      key_identifiers: [
        'Deep red to orange-red exterior colour — very vibrant and uniform',
        'Embossed tortoise shell pattern pressed on top surface',
        'Oval or round shape, dome-shaped top',
        'Placed on a green banana leaf square',
        'Chewy glutinous rice skin that slightly sticks to the banana leaf',
      ],
      common_lookalikes: ['Kueh Lapis', 'Mochi', 'Tang Yuan'],
      differentiators: 'Distinctive red-orange colour and embossed tortoise shell pattern on top are unmistakable; banana leaf base is a strong identifier; oval dome shape with patterned top surface unlike smooth mochi or round tang yuan; no layered appearance unlike kueh lapis.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -26 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 33 },
        ],
      },
    ],
  },
