  'asam-laksa': {
    id: 'asam-laksa',
    name: 'Asam Laksa',
    nameLocal: 'Asam Laksa',
    origin: 'Malaysia',
    flag: '🇲🇾',
    emoji: '🍜',
    color: '#0891B2',
    bgColor: '#CFFAFE',
    description: 'Penang-style sour tamarind fish broth with thick white rice noodles, shredded fish flakes, pineapple chunks, cucumber julienne and a dollop of prawn paste.',
    baseCalories: 380,
    calorieRange: { min: 280, max: 520 },
    macros: { protein: 22, carbs: 52, fat: 7, fiber: 4 },
    tags: ['Noodles', 'Sour', 'Penang', 'Seafood'],
    visual_detection: {
      protein: 'shredded white fish flakes scattered on top of noodles',
      starch: 'thick round white rice noodles (laksa noodles)',
      sauce: 'clear dark amber-brown sour tamarind fish broth, no coconut milk',
      sides: 'pineapple chunks, cucumber julienne, fresh mint leaves, red chilli slices, onion slices',
      plating: 'deep bowl with broth, prawn paste (petis) dollop on top',
      key_identifiers: [
        'clear sour amber broth (not creamy or opaque)',
        'visible pineapple chunks floating in bowl',
        'shredded fish flakes (not whole prawns)',
        'thick round white rice noodles',
        'dark prawn paste (petis) dollop on top',
      ],
      common_lookalikes: ['Curry Laksa', 'Laksa Lemak', 'Bun Bo Hue'],
      differentiators: 'Clear sour tamarind broth (not coconut milk based), pineapple pieces are the key visual giveaway, shredded fish instead of whole prawns or cockles.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -76 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 95 },
        ],
      },
    ],
  },

  'curry-laksa': {
    id: 'curry-laksa',
    name: 'Curry Laksa',
    nameLocal: 'Curry Laksa / Laksam',
    origin: 'Malaysia',
    flag: '🇲🇾',
    emoji: '🍜',
    color: '#0891B2',
    bgColor: '#CFFAFE',
    description: 'Rich yellow-orange coconut milk curry broth ladled over thick rice noodles or yellow noodles, topped with tofu puffs, cockles, bean sprouts and a hard-boiled egg.',
    baseCalories: 620,
    calorieRange: { min: 480, max: 820 },
    macros: { protein: 26, carbs: 62, fat: 28, fiber: 4 },
    tags: ['Noodles', 'Coconut', 'Spicy', 'Hawker'],
    visual_detection: {
      protein: 'cockles (small dark shellfish), hard-boiled egg halved',
      starch: 'thick round rice noodles or yellow egg noodles',
      sauce: 'opaque orange-yellow coconut milk curry broth, rich and creamy',
      sides: 'tofu puffs (golden spongy cubes), bean sprouts, sambal on side',
      plating: 'deep bowl filled with opaque orange-yellow broth',
      key_identifiers: [
        'opaque orange-yellow coconut milk broth (not clear)',
        'golden spongy tofu puffs floating in bowl',
        'cockles visible on top',
        'sambal chilli on the side or rim',
        'creamy rich broth surface',
      ],
      common_lookalikes: ['Laksa (Singapore)', 'Asam Laksa', 'Tom Kha'],
      differentiators: 'Opaque orange coconut milk broth distinguishes it from Asam Laksa (clear). Tofu puffs and cockles on top distinguish it from Singapore laksa.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -124 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 155 },
        ],
      },
    ],
  },

  'penang-char-kway-teow': {
    id: 'penang-char-kway-teow',
    name: 'Penang Char Kway Teow',
    nameLocal: 'Penang Char Koay Teow',
    origin: 'Malaysia',
    flag: '🇲🇾',
    emoji: '🥘',
    color: '#EA580C',
    bgColor: '#FFEDD5',
    description: 'Wok-fried flat rice noodles with duck egg, prawns, cockles, Chinese sausage and bean sprouts, cooked over high heat for an intense smoky wok hei flavour.',
    baseCalories: 680,
    calorieRange: { min: 520, max: 880 },
    macros: { protein: 28, carbs: 74, fat: 28, fiber: 3 },
    tags: ['Noodles', 'Wok Hei', 'Penang', 'Seafood'],
    visual_detection: {
      protein: 'whole prawns, cockles open in shell, sliced Chinese sausage (lap cheong)',
      starch: 'flat wide rice noodles (kway teow), slightly charred and dark',
      sauce: 'dark soy glaze coating noodles, slightly charred edges',
      sides: 'bean sprouts, chives (kuchai)',
      plating: 'served on plate or in bowl, dark oily noodles with visible char marks',
      key_identifiers: [
        'darker colour than Singapore CKT due to duck egg',
        'cockles open in shell visible on top',
        'strong char marks and wok hei appearance',
        'flat wide rice noodles very dark from soy and char',
        'duck egg gives richer darker colour',
      ],
      common_lookalikes: ['Char Kway Teow (Singapore)', 'Pad Thai', 'Beef Ho Fun'],
      differentiators: 'Darker colour from duck egg (not chicken egg), visible cockles in open shells, more charred appearance. Darker and richer than Singapore CKT.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -136 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 170 },
        ],
      },
    ],
  },

  'wonton-noodle-soup': {
    id: 'wonton-noodle-soup',
    name: 'Wonton Noodle Soup',
    nameLocal: 'Wantan Mee Soup',
    origin: 'Malaysia',
    flag: '🇲🇾',
    emoji: '🍜',
    color: '#EA580C',
    bgColor: '#FFEDD5',
    description: 'Springy egg noodles served in a clear pork-based broth with 3–4 plump pork and shrimp wontons, sliced char siew and blanched bok choy.',
    baseCalories: 420,
    calorieRange: { min: 320, max: 580 },
    macros: { protein: 24, carbs: 52, fat: 12, fiber: 2 },
    tags: ['Noodles', 'Soup', 'Dim Sum', 'Chinese'],
    visual_detection: {
      protein: 'pork and shrimp wontons (3-4 pieces, thin translucent skin), sliced char siew',
      starch: 'thin springy yellow egg noodles',
      sauce: 'clear pale golden pork broth',
      sides: 'bok choy blanched green',
      plating: 'deep bowl with clear broth, wontons visible below surface',
      key_identifiers: [
        'plump wontons with thin translucent wrappers visible',
        'clear (not cloudy) pale golden broth',
        'springy thin yellow egg noodles',
        'sliced char siew (red-edged roast pork)',
        'bok choy halves arranged in bowl',
      ],
      common_lookalikes: ['Wanton Mee dry version', 'Bak Chor Mee', 'Yee Mee Soup'],
      differentiators: 'Clear broth (not dark or opaque), wontons submerged in soup rather than tossed dry, always has both wontons and char siew together.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -84 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 105 },
        ],
      },
    ],
  },

  'pan-mee': {
    id: 'pan-mee',
    name: 'Pan Mee',
    nameLocal: '板面 Pan Mee',
    origin: 'Malaysia',
    flag: '🇲🇾',
    emoji: '🍜',
    color: '#EA580C',
    bgColor: '#FFEDD5',
    description: 'Hand-torn irregular flat wheat noodles in an anchovy broth, topped with minced pork, crispy dried anchovies, mushrooms and a poached egg.',
    baseCalories: 480,
    calorieRange: { min: 360, max: 640 },
    macros: { protein: 26, carbs: 58, fat: 16, fiber: 3 },
    tags: ['Noodles', 'Malaysian Chinese', 'Anchovy', 'Comfort Food'],
    visual_detection: {
      protein: 'minced pork scattered on top, poached egg in centre',
      starch: 'irregular torn flat wheat noodles (non-uniform shapes and sizes)',
      sauce: 'clear pale anchovy (ikan bilis) broth',
      sides: 'crispy dried anchovies (ikan bilis) on top, wood ear mushrooms, dark vinegar on the side',
      plating: 'deep bowl with clear broth, garnished with crispy ikan bilis on top',
      key_identifiers: [
        'irregular torn noodle shapes (not uniform cut)',
        'crispy dried anchovies (ikan bilis) garnish on top',
        'poached egg in the bowl',
        'clear anchovy broth (not dark)',
        'non-uniform rustic noodle pieces',
      ],
      common_lookalikes: ['Ban Mian', 'Yee Mee Soup', 'Flat Noodle Soup'],
      differentiators: 'Irregular hand-torn noodle shapes are the defining visual feature (not machine-cut). Ikan bilis garnish on top is unique. Poached egg in bowl.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -96 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 120 },
        ],
      },
    ],
  },

  'hakka-mee': {
    id: 'hakka-mee',
    name: 'Hakka Mee',
    nameLocal: '客家面 Hakka Mee',
    origin: 'Malaysia',
    flag: '🇲🇾',
    emoji: '🍜',
    color: '#EA580C',
    bgColor: '#FFEDD5',
    description: 'Springy yellow noodles tossed dry in lard and dark soy sauce with minced pork, crispy fried shallots and spring onion, served with a small clear soup on the side.',
    baseCalories: 460,
    calorieRange: { min: 340, max: 620 },
    macros: { protein: 22, carbs: 56, fat: 18, fiber: 2 },
    tags: ['Noodles', 'Dry', 'Malaysian Chinese', 'Hakka'],
    visual_detection: {
      protein: 'minced pork mixed through noodles',
      starch: 'springy yellow egg noodles, dry-tossed (no broth in main bowl)',
      sauce: 'dark soy glaze coating noodles, glistening with lard',
      sides: 'crispy golden fried shallots on top, chopped spring onion, small bowl of clear soup on the side',
      plating: 'plate or bowl of dry noodles with small soup bowl alongside',
      key_identifiers: [
        'dry noodles (not in broth) in main bowl',
        'glistening dark soy coating on yellow noodles',
        'crispy fried shallots topping',
        'small clear soup bowl served on the side',
        'minced pork throughout noodles',
      ],
      common_lookalikes: ['Wonton Mee dry', 'Mee Pok Dry', 'Bak Chor Mee'],
      differentiators: 'Dark soy and lard coating gives glossy appearance. Served with small side soup (not broth in main bowl). Minced pork rather than sliced or meatballs.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -92 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 115 },
        ],
      },
    ],
  },

  'nasi-kandar': {
    id: 'nasi-kandar',
    name: 'Nasi Kandar',
    nameLocal: 'Nasi Kandar',
    origin: 'Malaysia',
    flag: '🇲🇾',
    emoji: '🍛',
    color: '#F59E0B',
    bgColor: '#FEF3C7',
    description: 'Penang Muslim-style white rice flooded with multiple curries poured together ("banjir"), served with fried chicken or mutton and side vegetables, all sauces mixing on the plate.',
    baseCalories: 750,
    calorieRange: { min: 550, max: 1050 },
    macros: { protein: 38, carbs: 82, fat: 30, fiber: 4 },
    tags: ['Rice', 'Curry', 'Penang', 'Muslim'],
    visual_detection: {
      protein: 'fried chicken piece or mutton chunks, dark braised',
      starch: 'white jasmine rice mound on plate',
      sauce: 'multiple different curry sauces poured and mixing over rice — brown, orange, yellow hues all blending together',
      sides: 'stir-fried vegetables, papadums, boiled egg sometimes',
      plating: 'large round plate with rice mound flooded by mixed curries (banjir style)',
      key_identifiers: [
        'multiple different curry sauces all poured and mixed over rice',
        'curries visibly blending together on the plate ("banjir" flood style)',
        'fried chicken with dark curry-stained coating',
        'messy mixed-sauce appearance (intentional)',
        'Penang Muslim hawker style plating',
      ],
      common_lookalikes: ['Nasi Padang', 'Banana Leaf Rice', 'Nasi Campur'],
      differentiators: 'Multiple curries intentionally mixed and poured together over rice (banjir), creating a blended multi-sauce appearance. Different from Nasi Padang where curries are kept separate.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -150 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 188 },
        ],
      },
    ],
  },

  'roti-canai': {
    id: 'roti-canai',
    name: 'Roti Canai',
    nameLocal: 'Roti Canai',
    origin: 'Malaysia',
    flag: '🇲🇾',
    emoji: '🫓',
    color: '#DC2626',
    bgColor: '#FEE2E2',
    description: 'Flaky multi-layered flatbread with crisp exterior and soft interior, served with dal curry and fish curry for dipping.',
    baseCalories: 300,
    calorieRange: { min: 220, max: 440 },
    macros: { protein: 8, carbs: 42, fat: 12, fiber: 2 },
    tags: ['Indian', 'Bread', 'Mamak', 'Vegetarian'],
    visual_detection: {
      protein: 'none (bread only)',
      starch: 'flaky layered flatbread, roughly circular with irregular torn edges',
      sauce: 'none on bread itself; dal curry (yellow-brown) and fish curry (dark orange) in small side bowls',
      sides: 'small bowl of yellow dal curry, small bowl of dark fish curry',
      plating: 'flatbread on plate or tray, two small curry dipping bowls alongside',
      key_identifiers: [
        'very flaky visible layers throughout bread',
        'torn irregular edges (not smooth like naan)',
        'golden-brown colour from griddle cooking',
        'two separate dipping curry bowls (dal and fish curry)',
        'slightly crispy exterior with soft flaky interior',
      ],
      common_lookalikes: ['Roti Prata', 'Chapati', 'Naan', 'Paratha'],
      differentiators: 'More flaky and layered than chapati. Torn irregular edges (not smooth). Always served with both dal and fish curry dips together (not just one). Similar to roti prata but slightly different texture.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -60 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 75 },
        ],
      },
    ],
  },

  'banana-leaf-rice': {
    id: 'banana-leaf-rice',
    name: 'Banana Leaf Rice',
    nameLocal: 'Nasi Daun Pisang',
    origin: 'Malaysia',
    flag: '🇲🇾',
    emoji: '🍛',
    color: '#F59E0B',
    bgColor: '#FEF3C7',
    description: 'White rice mounded on a large green banana leaf, surrounded by small portions of vegetable curries, papadums, rasam, pickle, and a choice of fried chicken or fish.',
    baseCalories: 680,
    calorieRange: { min: 500, max: 920 },
    macros: { protein: 30, carbs: 86, fat: 22, fiber: 6 },
    tags: ['Rice', 'Indian', 'Malaysian Indian', 'Banana Leaf'],
    visual_detection: {
      protein: 'fried chicken drumstick or fried fish fillet',
      starch: 'white jasmine rice mound in centre of banana leaf',
      sauce: 'multiple small vegetable curry portions arranged around rice, rasam (thin dark soup) in small cup',
      sides: 'papadums (thin crispy disc), pickle, various vegetable curries, rasam',
      plating: 'large fresh green banana leaf as the plate, food arranged on top of leaf',
      key_identifiers: [
        'distinctive large green banana leaf as the plate/base',
        'multiple small curry portions arranged around central rice mound',
        'thin crispy papadum disc on leaf',
        'bright green banana leaf visible around food edges',
        'South Indian Tamil style arrangement',
      ],
      common_lookalikes: ['Nasi Padang', 'Nasi Kandar', 'Thali'],
      differentiators: 'The large fresh green banana leaf as the serving plate is the unmistakable identifier. Multiple small curry portions arranged around rice. Papadum always present.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -136 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 170 },
        ],
      },
    ],
  },

  'cendol-malaysian': {
    id: 'cendol-malaysian',
    name: 'Cendol',
    nameLocal: 'Cendol',
    origin: 'Malaysia',
    flag: '🇲🇾',
    emoji: '🍧',
    color: '#EC4899',
    bgColor: '#FCE7F3',
    description: 'Shaved ice dessert with green pandan worm-like jelly strands, coconut milk poured over and dark gula melaka palm sugar syrup drizzled on top, with red beans.',
    baseCalories: 320,
    calorieRange: { min: 220, max: 460 },
    macros: { protein: 3, carbs: 62, fat: 8, fiber: 2 },
    tags: ['Dessert', 'Pandan', 'Coconut', 'Shaved Ice'],
    visual_detection: {
      protein: 'none',
      starch: 'green pandan jelly noodle strands (worm-like, short segments)',
      sauce: 'white coconut milk poured over ice, dark brown gula melaka (palm sugar) syrup drizzled on top',
      sides: 'red kidney beans or red beans',
      plating: 'bowl or tall glass of shaved ice with colourful toppings visible',
      key_identifiers: [
        'distinctive bright green pandan jelly worm-like strands',
        'dark brown gula melaka palm sugar syrup (not white condensed milk)',
        'white coconut milk visible',
        'shaved ice mound as base',
        'red beans among the toppings',
      ],
      common_lookalikes: ['Ice Kachang (ABC)', 'Chendol Singapore version', 'Buko Pandan'],
      differentiators: 'Green pandan jelly noodle strands are the defining feature. Dark palm sugar (gula melaka) syrup — not condensed milk or rose syrup. Simpler toppings than ABC.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -64 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 80 },
        ],
      },
    ],
  },

  'abc-air-batu-campur': {
    id: 'abc-air-batu-campur',
    name: 'ABC (Air Batu Campur)',
    nameLocal: 'ABC / Air Batu Campur',
    origin: 'Malaysia',
    flag: '🇲🇾',
    emoji: '🍧',
    color: '#EC4899',
    bgColor: '#FCE7F3',
    description: 'Malaysian shaved ice mound topped with attap chee palm seeds, sweet corn, red beans, grass jelly, coloured jelly cubes, drizzled with condensed milk and rose syrup.',
    baseCalories: 350,
    calorieRange: { min: 250, max: 500 },
    macros: { protein: 4, carbs: 72, fat: 6, fiber: 3 },
    tags: ['Dessert', 'Shaved Ice', 'Malaysian', 'Hawker'],
    visual_detection: {
      protein: 'none',
      starch: 'none (jelly cubes and palm seeds as toppings)',
      sauce: 'white condensed milk drizzled over, pink or red rose syrup',
      sides: 'attap chee (translucent white palm seeds), sweet corn kernels, red beans, grass jelly (black cubes), coloured jelly cubes (green, yellow, red)',
      plating: 'tall mound of shaved ice in bowl with colourful toppings visible throughout',
      key_identifiers: [
        'tall mound of shaved ice as base',
        'multiple colourful toppings: corn, red beans, jelly cubes',
        'translucent white attap chee palm seeds visible',
        'pink rose syrup drizzle',
        'white condensed milk drizzle',
      ],
      common_lookalikes: ['Cendol', 'Patbingsu (Korean)', 'Ice Kachang Singapore'],
      differentiators: 'More toppings and more colourful than Cendol. Has corn, attap chee and coloured jelly cubes that Cendol lacks. Rose syrup and condensed milk (not palm sugar). No green pandan jelly strands.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -70 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 88 },
        ],
      },
    ],
  },

  'bun-bo-hue': {
    id: 'bun-bo-hue',
    name: 'Bun Bo Hue',
    nameLocal: 'Bún Bò Huế',
    origin: 'Vietnam',
    flag: '🇻🇳',
    emoji: '🍲',
    color: '#0891B2',
    bgColor: '#CFFAFE',
    description: 'Spicy lemongrass-infused pork and beef broth coloured bright orange-red, served with thick round rice noodles, pork hock slices, beef, congealed pork blood and fresh herbs.',
    baseCalories: 480,
    calorieRange: { min: 360, max: 640 },
    macros: { protein: 32, carbs: 52, fat: 16, fiber: 3 },
    tags: ['Soup', 'Spicy', 'Vietnamese', 'Beef'],
    visual_detection: {
      protein: 'sliced pork hock (round bone cross-section visible), sliced beef, dark cubes of congealed pork blood',
      starch: 'thick round rice noodles (bun, thicker than pho noodles)',
      sauce: 'bright orange-red spicy lemongrass broth, opaque',
      sides: 'banana blossom shreds, bean sprouts, fresh mint and Vietnamese herbs, lime wedges, chilli',
      plating: 'large deep bowl with vibrant orange-red broth',
      key_identifiers: [
        'bright orange-red spicy broth (distinctive colour, not clear)',
        'thick round rice noodles (thicker than pho flat noodles)',
        'pork hock with visible round bone cross-section',
        'dark brown congealed blood cubes',
        'banana blossom shreds as garnish',
      ],
      common_lookalikes: ['Pho Bo', 'Tom Yum Soup', 'Beef Noodle Soup'],
      differentiators: 'Bright orange-red spicy broth (not clear like pho). Thick round noodles (not flat pho noodles). Pork hock piece is distinctive. Congealed blood cubes present.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -96 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 120 },
        ],
      },
    ],
  },

  'mi-quang': {
    id: 'mi-quang',
    name: 'Mi Quang',
    nameLocal: 'Mì Quảng',
    origin: 'Vietnam',
    flag: '🇻🇳',
    emoji: '🍜',
    color: '#EA580C',
    bgColor: '#FFEDD5',
    description: 'Wide flat yellow turmeric-tinted rice noodles with a small amount of savoury broth, shrimp and pork, topped with crushed peanuts, fresh herbs and a sesame rice cracker.',
    baseCalories: 420,
    calorieRange: { min: 320, max: 560 },
    macros: { protein: 24, carbs: 54, fat: 14, fiber: 4 },
    tags: ['Noodles', 'Vietnamese', 'Turmeric', 'Central Vietnam'],
    visual_detection: {
      protein: 'whole prawns or shrimp, sliced pork belly',
      starch: 'wide flat yellow noodles (turmeric-tinted), minimal broth (almost dry)',
      sauce: 'very small amount of turmeric-yellow broth at bottom (not a soup bowl)',
      sides: 'crushed peanuts scattered on top, fresh herbs (mint, cilantro), bean sprouts, sesame rice cracker (banh trang) placed on rim or on top',
      plating: 'wide shallow bowl with very little broth, sesame rice cracker on top or side',
      key_identifiers: [
        'yellow turmeric-tinted wide flat noodles',
        'minimal broth — almost dry (not a soup)',
        'sesame rice cracker (banh trang) on top or alongside',
        'crushed peanuts topping',
        'wide shallow bowl presentation',
      ],
      common_lookalikes: ['Pho', 'Bun Bo Hue', 'Pad See Ew'],
      differentiators: 'Yellow turmeric-coloured noodles distinguish it from white pho noodles. Minimal broth (not a soup) is key. Sesame rice cracker on top is a unique identifier.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -84 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 105 },
        ],
      },
    ],
  },

  'banh-xeo': {
    id: 'banh-xeo',
    name: 'Banh Xeo',
    nameLocal: 'Bánh Xèo',
    origin: 'Vietnam',
    flag: '🇻🇳',
    emoji: '🥞',
    color: '#EA580C',
    bgColor: '#FFEDD5',
    description: 'Large sizzling crispy golden-yellow turmeric rice flour crepe folded in half, stuffed with bean sprouts, shrimp and pork, wrapped in mustard leaf and dipped in fish sauce.',
    baseCalories: 350,
    calorieRange: { min: 250, max: 500 },
    macros: { protein: 18, carbs: 36, fat: 16, fiber: 3 },
    tags: ['Snack', 'Vietnamese', 'Crepe', 'Crispy'],
    visual_detection: {
      protein: 'whole shrimp and sliced pork inside fold',
      starch: 'large thin crispy rice flour crepe, bright yellow from turmeric, folded in half',
      sauce: 'clear fish sauce dipping sauce (nuoc cham) in small bowl',
      sides: 'mustard leaf or lettuce for wrapping, fresh herbs, bean sprouts visible at fold opening',
      plating: 'large folded yellow crepe on plate, dipping sauce bowl alongside',
      key_identifiers: [
        'large folded half-moon shape, bright golden-yellow colour',
        'very crispy thin exterior',
        'bean sprouts visible peeking out from fold',
        'turmeric yellow colour throughout crepe',
        'mustard leaf / lettuce wrapping leaves on the side',
      ],
      common_lookalikes: ['Vietnamese omelette', 'Roti Canai', 'Pad Thai crepe'],
      differentiators: 'Large folded yellow crispy crepe (not a soft pancake or omelette). Turmeric yellow colour. Bean sprouts visible at the fold. Mustard leaf for wrapping on the side.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -70 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 88 },
        ],
      },
    ],
  },

  'goi-cuon': {
    id: 'goi-cuon',
    name: 'Goi Cuon',
    nameLocal: 'Gỏi Cuốn',
    origin: 'Vietnam',
    flag: '🇻🇳',
    emoji: '🌯',
    color: '#EA580C',
    bgColor: '#FFEDD5',
    description: 'Fresh transparent rice paper rolls tightly packed with pink prawns, vermicelli, green herbs and lettuce, served with hoisin peanut dipping sauce.',
    baseCalories: 120,
    calorieRange: { min: 80, max: 180 },
    macros: { protein: 8, carbs: 16, fat: 3, fiber: 1 },
    tags: ['Snack', 'Fresh', 'Vietnamese', 'Light'],
    visual_detection: {
      protein: 'pink whole prawns clearly visible through transparent rice paper wrapper',
      starch: 'thin rice vermicelli inside, transparent rice paper wrapper outside',
      sauce: 'thick dark brown hoisin peanut dipping sauce in small bowl',
      sides: 'green herbs and lettuce visible through wrapper',
      plating: 'tight cylindrical rolls (2-3) on plate, dipping sauce bowl alongside',
      key_identifiers: [
        'transparent rice paper wrapper — contents clearly visible through it',
        'pink prawns distinctly visible through wrapper',
        'tight cylindrical compact shape',
        'green herbs and white vermicelli visible through wrapper',
        'not fried (no golden crust)',
      ],
      common_lookalikes: ['Popiah', 'Spring Rolls (fried)', 'Vietnamese fried spring rolls'],
      differentiators: 'Transparent rice paper (not wheat wrapper). Pink prawn and green herbs clearly visible through the wrapper. Not fried — no golden crispy exterior. Served fresh/cold.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -24 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 30 },
        ],
      },
    ],
  },

  'hu-tieu': {
    id: 'hu-tieu',
    name: 'Hu Tieu',
    nameLocal: 'Hủ Tiếu',
    origin: 'Vietnam',
    flag: '🇻🇳',
    emoji: '🍜',
    color: '#0891B2',
    bgColor: '#CFFAFE',
    description: 'Clear pork and seafood broth with flat dry rice noodles, sliced pork, prawns, squid, quail eggs and fried shallots — a southern Vietnamese staple.',
    baseCalories: 430,
    calorieRange: { min: 320, max: 580 },
    macros: { protein: 28, carbs: 52, fat: 12, fiber: 2 },
    tags: ['Soup', 'Vietnamese', 'Seafood', 'Southern Vietnam'],
    visual_detection: {
      protein: 'sliced pork, whole prawns, squid rings, small quail eggs halved',
      starch: 'flat thin dry rice noodles or thin round rice noodles',
      sauce: 'clear pale pork and seafood broth',
      sides: 'fried shallots on top, fresh herbs, bean sprouts, lime wedge',
      plating: 'deep bowl with clear broth, assorted protein toppings visible',
      key_identifiers: [
        'clear (not cloudy or coloured) pale broth',
        'mixed seafood and pork toppings together',
        'quail eggs halved visible in bowl',
        'fried shallots garnish',
        'flat or thin round rice noodles (not egg noodles)',
      ],
      common_lookalikes: ['Pho', 'Wonton Noodle Soup', 'Bun Bo Hue'],
      differentiators: 'Clear broth (not spiced red like Bun Bo Hue, not aromatic star anise like pho). Mixed seafood and pork together. Quail eggs are a distinctive identifier.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -86 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 108 },
        ],
      },
    ],
  },

  'com-ga-hoi-an': {
    id: 'com-ga-hoi-an',
    name: 'Com Ga Hoi An',
    nameLocal: 'Cơm Gà Hội An',
    origin: 'Vietnam',
    flag: '🇻🇳',
    emoji: '🍚',
    color: '#F59E0B',
    bgColor: '#FEF3C7',
    description: 'Hoi An-style pale yellow turmeric-tinted rice topped with shredded poached chicken, crispy fried shallots, fresh herbs and a lime wedge, with chilli sauce on the side.',
    baseCalories: 460,
    calorieRange: { min: 340, max: 620 },
    macros: { protein: 32, carbs: 54, fat: 12, fiber: 2 },
    tags: ['Rice', 'Vietnamese', 'Chicken', 'Hoi An'],
    visual_detection: {
      protein: 'shredded poached chicken (not sliced), pale white-yellow pulled strands',
      starch: 'pale yellow turmeric-tinted rice (not white)',
      sauce: 'chilli sauce on side, light chicken broth sometimes drizzled',
      sides: 'crispy golden fried shallots on top, fresh herbs (Vietnamese coriander, mint), lime wedge',
      plating: 'plate with yellow rice mound topped with shredded chicken and garnish',
      key_identifiers: [
        'yellow turmeric-tinted rice (not white rice)',
        'shredded (pulled) chicken — not sliced pieces',
        'crispy fried shallots on top',
        'fresh herb garnish',
        'lime wedge on the side',
      ],
      common_lookalikes: ['Hainanese Chicken Rice', 'Com Ga (plain chicken rice)', 'Com Tam'],
      differentiators: 'Yellow turmeric rice (not white) is the key differentiator. Shredded chicken (not sliced or whole piece). Hoi An specific style with herb garnish.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -92 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 115 },
        ],
      },
    ],
  },
