  'nasi-padang': {
    id: 'nasi-padang',
    name: 'Nasi Padang',
    nameLocal: 'Nasi Padang',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍛',
    color: '#16A34A',
    bgColor: '#DCFCE7',
    description: 'White steamed rice served with a selection of Padang-style dishes including rendang, gulai, sambal, and fried fish arranged around or on the plate.',
    baseCalories: 700,
    calorieRange: { min: 500, max: 1000 },
    macros: { protein: 32, carbs: 74, fat: 28, fiber: 4 },
    tags: ['Malay', 'Rice', 'Padang', 'Mixed'],
    visual_detection: {
      protein: 'rendang beef chunks, fried fish fillet, or gulai chicken pieces — multiple proteins present',
      starch: 'white steamed jasmine rice, mounded in centre of plate',
      sauce: 'multiple sauces: dark brown rendang, orange-red sambal, yellow gulai, each in separate small portions',
      sides: 'multiple small side dishes arranged around rice — at least 3–5 different items',
      plating: 'flat plate or tray with rice in centre surrounded by individual small portions of various curries and sides',
      key_identifiers: [
        'multiple distinct curry/sambal portions arranged around rice',
        'dark brown dry rendang alongside wet curries',
        'variety of colours from different dishes on same plate',
        'fried fish or egg often present alongside meat',
        'no single dominant sauce — each component separate',
      ],
      common_lookalikes: ['Nasi Campur', 'Nasi Goreng', 'Banana Leaf Rice'],
      differentiators: 'Nasi Padang has multiple individual wet and dry Padang-style dishes arranged around plain white rice — unlike nasi goreng (fried rice) or banana leaf rice (Indian-style curries on a leaf).',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -140 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 175 },
        ],
      },
    ],
  },

  'mee-rebus': {
    id: 'mee-rebus',
    name: 'Mee Rebus',
    nameLocal: 'Mee Rebus',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍜',
    color: '#EA580C',
    bgColor: '#FFEDD5',
    description: 'Yellow egg noodles smothered in a thick, dark-brown sweet-spicy gravy made from sweet potato, topped with hard-boiled egg, fried tofu, bean sprouts, green chilli, and lime.',
    baseCalories: 480,
    calorieRange: { min: 350, max: 650 },
    macros: { protein: 20, carbs: 68, fat: 12, fiber: 4 },
    tags: ['Noodles', 'Malay', 'Spicy', 'Gravy'],
    visual_detection: {
      protein: 'hard-boiled egg halved, fried tofu cubes',
      starch: 'thick yellow egg noodles',
      sauce: 'thick dark brown gravy, almost opaque, sweet-spicy aroma, sweet potato based — notably darker and thicker than most noodle sauces',
      sides: 'bean sprouts, sliced green chilli, lime wedge, fried shallots',
      plating: 'deep bowl or plate with noodles mostly submerged in thick gravy',
      key_identifiers: [
        'thick dark brown sweet gravy coating noodles (not clear or red-orange)',
        'yellow egg noodles visible underneath',
        'hard-boiled egg half placed on top',
        'bean sprouts and green chilli as garnish',
        'lime wedge on side',
      ],
      common_lookalikes: ['Mee Goreng', 'Lor Mee'],
      differentiators: 'Thick dark brown sweet-potato-based gravy (not orange-red like mee goreng, not starchy-gluey dark like lor mee), always with hard-boiled egg half and lime.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -96 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 120 },
        ],
      },
    ],
  },

  'mee-siam': {
    id: 'mee-siam',
    name: 'Mee Siam',
    nameLocal: 'Mee Siam',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍜',
    color: '#EA580C',
    bgColor: '#FFEDD5',
    description: 'Thin white rice vermicelli in a tangy, mildly spicy reddish-pink tamarind and shrimp paste gravy, garnished with dried prawns, tau pok, hard-boiled egg, and lime.',
    baseCalories: 420,
    calorieRange: { min: 300, max: 580 },
    macros: { protein: 16, carbs: 62, fat: 10, fiber: 3 },
    tags: ['Noodles', 'Malay', 'Tangy', 'Spicy'],
    visual_detection: {
      protein: 'hard-boiled egg half, dried prawns (small pink/orange)',
      starch: 'thin white rice vermicelli (bee hoon)',
      sauce: 'tangy reddish-pink gravy — lighter in colour than mee rebus, watery-to-medium consistency with tamarind tang',
      sides: 'tau pok (fried tofu puffs), sliced green chilli, lime wedge, bean sprouts',
      plating: 'bowl or deep plate with thin vermicelli in reddish-pink sauce',
      key_identifiers: [
        'thin white rice vermicelli (not thick yellow egg noodles)',
        'reddish-pink tangy gravy',
        'tau pok (fried tofu puffs) visible',
        'hard-boiled egg half on top',
        'lime wedge always present',
      ],
      common_lookalikes: ['Mee Rebus', 'Bee Hoon Soup'],
      differentiators: 'Thin rice vermicelli (not yellow noodles), tangy pinkish-red sauce (not dark brown sweet gravy), tau pok pieces are a key identifier.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -84 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 105 },
        ],
      },
    ],
  },

  'rojak': {
    id: 'rojak',
    name: 'Rojak',
    nameLocal: 'Rojak',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🥗',
    color: '#16A34A',
    bgColor: '#DCFCE7',
    description: 'A tangy mixed salad of cucumber, turnip, pineapple, tau pok, and you tiao pieces tossed in a thick, pungent dark shrimp paste sauce and topped with crushed peanuts.',
    baseCalories: 320,
    calorieRange: { min: 220, max: 480 },
    macros: { protein: 10, carbs: 42, fat: 12, fiber: 5 },
    tags: ['Malay', 'Salad', 'Snack', 'Fruity'],
    visual_detection: {
      protein: 'tau pok (fried tofu puffs) cubed, you tiao (dough fritter) pieces',
      starch: 'you tiao strips, none dominant',
      sauce: 'thick dark brown-black shrimp paste (belacan) sauce coating all ingredients — very dark, glossy, slightly clumpy',
      sides: 'none',
      plating: 'plate or tray, mixed components all coated in dark sauce, crushed peanuts heaped on top',
      key_identifiers: [
        'thick very dark brown-black sauce coating all ingredients',
        'crushed peanuts generously sprinkled on top',
        'visible fruit pieces — pineapple and turnip (jicama)',
        'cucumber chunks alongside fruit',
        'you tiao (dough fritter) pieces visible',
      ],
      common_lookalikes: ['Gado Gado', 'Salad with peanut sauce'],
      differentiators: 'Rojak sauce is very dark near-black (belacan-based), not the lighter tan peanut sauce of gado gado; always contains mixed fruit and you tiao.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -64 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 80 },
        ],
      },
    ],
  },

  'popiah-fresh': {
    id: 'popiah-fresh',
    name: 'Popiah (Fresh)',
    nameLocal: 'Popiah',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🌯',
    color: '#16A34A',
    bgColor: '#DCFCE7',
    description: 'A fresh (unfried) spring roll in a soft thin wheat flour wrapper, packed with braised shredded jicama, carrot, bean sprouts, egg, and prawns, sealed with sweet dark sauce and chilli.',
    baseCalories: 200,
    calorieRange: { min: 140, max: 300 },
    macros: { protein: 8, carbs: 28, fat: 6, fiber: 3 },
    tags: ['Snack', 'Malay', 'Fresh Roll', 'Light'],
    visual_detection: {
      protein: 'small prawns, thin egg strips inside roll',
      starch: 'soft thin wheat flour wrapper (opaque white, not translucent rice paper)',
      sauce: 'sweet dark soy sauce and chilli visible at the open ends of the roll',
      sides: 'none',
      plating: 'roll served whole or sliced into sections on a plate, compact and tightly packed',
      key_identifiers: [
        'opaque white wheat flour wrapper (not translucent rice paper)',
        'tightly packed cylindrical roll',
        'sweet dark sauce and chilli visible at ends',
        'shredded jicama/turnip filling visible when cut',
        'not deep-fried — pale and soft exterior',
      ],
      common_lookalikes: ['Cheung Fun', 'Vietnamese Fresh Spring Roll (Goi Cuon)'],
      differentiators: 'Wheat (not rice paper) wrapper is opaque and soft; filling is dense braised jicama with sweet dark sauce inside — unlike translucent Vietnamese rolls or rice noodle cheung fun.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -40 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 50 },
        ],
      },
    ],
  },

  'otah-otah': {
    id: 'otah-otah',
    name: 'Otah-Otah',
    nameLocal: 'Otah / Otak-Otak',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🐟',
    color: '#D97706',
    bgColor: '#FEF3C7',
    description: 'Spiced fish paste mixed with coconut milk and aromatics, wrapped in banana leaf and grilled until the leaf is charred, revealing a fragrant orange-red fish cake inside.',
    baseCalories: 120,
    calorieRange: { min: 80, max: 180 },
    macros: { protein: 10, carbs: 6, fat: 6, fiber: 1 },
    tags: ['Snack', 'Malay', 'Grilled', 'Seafood'],
    visual_detection: {
      protein: 'fish paste cake — orange-red, moist, flaked texture',
      starch: 'none',
      sauce: 'none — fish paste is self-contained with spices and coconut milk',
      sides: 'none',
      plating: 'wrapped in banana leaf, leaf charred/blackened on outside; fish cake exposed when leaf is peeled open',
      key_identifiers: [
        'charred or grilled banana leaf wrapping',
        'orange-red spiced fish paste visible when opened',
        'flat rectangular or elongated parcel shape',
        'smoky grilled aroma',
        'leaf has char marks from grilling',
      ],
      common_lookalikes: ['Pepes Ikan (Indonesian fish in banana leaf)', 'Lo Mai Gai'],
      differentiators: 'Otah is a flat grilled banana leaf parcel containing orange-red fish paste — much thinner and flatter than lo mai gai; the fish paste colour is distinctive orange-red from turmeric and chilli.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -24 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 30 },
        ],
      },
    ],
  },

  'nasi-goreng-kampung': {
    id: 'nasi-goreng-kampung',
    name: 'Nasi Goreng Kampung',
    nameLocal: 'Nasi Goreng Kampung',
    origin: 'Malaysia',
    flag: '🇲🇾',
    emoji: '🍳',
    color: '#16A34A',
    bgColor: '#DCFCE7',
    description: 'Rustic village-style Malaysian fried rice darkened with soy sauce and belacan (shrimp paste), studded with crispy dried anchovies, green vegetables, and topped with a fried egg.',
    baseCalories: 580,
    calorieRange: { min: 420, max: 780 },
    macros: { protein: 22, carbs: 76, fat: 20, fiber: 3 },
    tags: ['Malay', 'Rice', 'Fried', 'Kampung'],
    visual_detection: {
      protein: 'fried egg (sunny-side up on top), small dried anchovies (ikan bilis) mixed throughout rice',
      starch: 'dark fried rice, grains separated',
      sauce: 'dark soy and belacan coating — rice is dark brown to near-black, darker than standard nasi goreng',
      sides: 'keropok (prawn crackers) on the side, sliced cucumber, lime wedge',
      plating: 'flat plate with fried rice mounded, fried egg on top, keropok to the side',
      key_identifiers: [
        'very dark rice from belacan and soy (darker than standard nasi goreng)',
        'crispy dried anchovies (ikan bilis) visible throughout',
        'fried egg on top',
        'green leafy vegetables (kangkong) mixed in',
        'keropok crackers on the side',
      ],
      common_lookalikes: ['Nasi Goreng (standard)', 'Nasi Goreng Indonesia'],
      differentiators: 'Darker rice than standard nasi goreng due to belacan; crispy ikan bilis is the defining ingredient mixed throughout; more rustic and homestyle appearance.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -116 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 145 },
        ],
      },
    ],
  },

  'kuih-tutu': {
    id: 'kuih-tutu',
    name: 'Kuih Tutu',
    nameLocal: 'Kuih Tutu',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍥',
    color: '#D97706',
    bgColor: '#FEF3C7',
    description: 'Small steamed rice flour cakes pressed into flower or cone shapes with a soft white exterior and a sweet peanut or grated coconut filling inside.',
    baseCalories: 80,
    calorieRange: { min: 55, max: 120 },
    macros: { protein: 2, carbs: 14, fat: 2, fiber: 1 },
    tags: ['Snack', 'Malay', 'Steamed', 'Kuih'],
    visual_detection: {
      protein: 'none',
      starch: 'steamed rice flour cake, white exterior',
      sauce: 'none',
      sides: 'none',
      plating: 'small individual cakes on a plate or tray, often in sets of 3–6, flower or cone shaped',
      key_identifiers: [
        'small flower or cone shaped white rice cake',
        'white opaque exterior from steamed rice flour',
        'peanut or coconut filling visible at top opening or when bitten',
        'very small size (3–5 cm)',
        'sold in batches of multiple pieces',
      ],
      common_lookalikes: ['Putu Piring', 'Ang Ku Kueh'],
      differentiators: 'Kuih tutu is flower or cone shaped (not disc/round) with a plain white exterior and no visible palm sugar — unlike putu piring which is disc-shaped with visible brown sugar centre.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -16 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 20 },
        ],
      },
    ],
  },

  'putu-piring': {
    id: 'putu-piring',
    name: 'Putu Piring',
    nameLocal: 'Putu Piring',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍥',
    color: '#D97706',
    bgColor: '#FEF3C7',
    description: 'Round disc-shaped steamed rice flour cakes with a soft white exterior and a molten dark palm sugar (gula melaka) centre, served with freshly grated coconut.',
    baseCalories: 90,
    calorieRange: { min: 60, max: 140 },
    macros: { protein: 2, carbs: 17, fat: 2, fiber: 1 },
    tags: ['Snack', 'Malay', 'Steamed', 'Palm Sugar'],
    visual_detection: {
      protein: 'none',
      starch: 'steamed rice flour disc, white exterior',
      sauce: 'none — dark brown palm sugar filling inside',
      sides: 'fresh grated white coconut served alongside or on top',
      plating: 'small round flat discs on banana leaf or plate, often in sets, white coconut alongside',
      key_identifiers: [
        'round flat disc shape (not cone or flower)',
        'white steamed rice flour exterior',
        'dark brown palm sugar visible at centre depression or when broken open',
        'white grated coconut served alongside',
        'steam lines sometimes visible from fresh serving',
      ],
      common_lookalikes: ['Kuih Tutu', 'Ondeh Ondeh'],
      differentiators: 'Putu piring is flat and disc-shaped with a visible dark brown palm sugar centre — always served with grated coconut; kuih tutu is cone/flower shaped without visible sugar.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -18 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 23 },
        ],
      },
    ],
  },

  'epok-epok': {
    id: 'epok-epok',
    name: 'Epok-Epok',
    nameLocal: 'Epok-Epok / Karipap',
    origin: 'Malaysia',
    flag: '🇲🇾',
    emoji: '🥙',
    color: '#D97706',
    bgColor: '#FEF3C7',
    description: 'A deep-fried half-moon shaped pastry with golden-brown crimped edges, filled with spiced curried potato and egg — the Malay version of a curry puff.',
    baseCalories: 180,
    calorieRange: { min: 130, max: 260 },
    macros: { protein: 5, carbs: 22, fat: 8, fiber: 2 },
    tags: ['Snack', 'Malay', 'Fried', 'Pastry'],
    visual_detection: {
      protein: 'diced hard-boiled egg inside pastry (visible when cut)',
      starch: 'deep-fried pastry shell, golden brown; spiced potato filling inside',
      sauce: 'none',
      sides: 'none',
      plating: 'individual half-moon pastry on plate or in paper bag, served individually',
      key_identifiers: [
        'half-moon (semicircle) shape',
        'deep golden-brown fried pastry exterior',
        'distinctive crimped/pleated edge along the curved side',
        'small to medium size (palm-sized)',
        'yellow spiced potato and egg filling visible when cut',
      ],
      common_lookalikes: ['Curry Puff (Old Chang Kee style)', 'Samosa'],
      differentiators: 'Epok-epok is half-moon shaped with crimped edges and deep-fried golden crust — curry puffs may be round or larger; samosas are triangular.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -36 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 45 },
        ],
      },
    ],
  },

  'mee-bandung': {
    id: 'mee-bandung',
    name: 'Mee Bandung Muar',
    nameLocal: 'Mee Bandung Muar',
    origin: 'Malaysia',
    flag: '🇲🇾',
    emoji: '🍜',
    color: '#EA580C',
    bgColor: '#FFEDD5',
    description: 'Yellow egg noodles in a rich, thick orange-red broth made from prawns and tomato, served with fried tofu, hard-boiled egg, bean sprouts, and whole prawns.',
    baseCalories: 520,
    calorieRange: { min: 380, max: 700 },
    macros: { protein: 24, carbs: 66, fat: 16, fiber: 3 },
    tags: ['Noodles', 'Malay', 'Prawn', 'Muar'],
    visual_detection: {
      protein: 'whole prawns (shell-on or peeled), hard-boiled egg half, fried tofu cubes',
      starch: 'thick yellow egg noodles',
      sauce: 'rich thick orange-red broth — brighter and more tomato-forward than prawn bisque, opaque from prawn stock',
      sides: 'bean sprouts, fried shallots, sliced green chilli',
      plating: 'deep bowl with yellow noodles in orange-red broth, prawns and egg visible on top',
      key_identifiers: [
        'bright orange-red thick broth (prawn and tomato based)',
        'thick yellow egg noodles',
        'whole prawns visible on top',
        'hard-boiled egg half',
        'fried tofu pieces in broth',
      ],
      common_lookalikes: ['Prawn Noodle Soup', 'Mee Rebus', 'Tom Yum Noodles'],
      differentiators: 'Brighter orange-red colour than mee rebus (which is dark brown), and thicker broth than clear prawn noodle soup; whole prawns are always present.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -104 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 130 },
        ],
      },
    ],
  },

  'soto-betawi': {
    id: 'soto-betawi',
    name: 'Soto Betawi',
    nameLocal: 'Soto Betawi',
    origin: 'Indonesia',
    flag: '🇮🇩',
    emoji: '🍲',
    color: '#0891B2',
    bgColor: '#CFFAFE',
    description: 'A rich Indonesian beef soup from Jakarta with an opaque white coconut milk broth, featuring tender beef and offal slices, potato chunks, tomato, and crispy emping crackers on the side.',
    baseCalories: 480,
    calorieRange: { min: 350, max: 680 },
    macros: { protein: 30, carbs: 32, fat: 24, fiber: 2 },
    tags: ['Soup', 'Indonesian', 'Beef', 'Coconut'],
    visual_detection: {
      protein: 'beef slices, offal (tripe/lung) pieces, all pale to light brown from coconut broth',
      starch: 'potato chunks in broth, sometimes fried potato cubes',
      sauce: 'opaque milky white to pale yellow coconut milk broth — creamy, not clear',
      sides: 'emping (melinjo crackers) on the side, sliced tomato, fried shallots, lime wedge, sambal',
      plating: 'deep bowl with white milky broth, beef and offal visible, emping crackers on side plate or rim',
      key_identifiers: [
        'opaque white/pale yellow coconut milk broth (not clear)',
        'beef and offal slices in creamy broth',
        'potato chunks present',
        'emping (thin wafer crackers) on the side',
        'tomato slices and fried shallots as garnish',
      ],
      common_lookalikes: ['Soto Ayam', 'Bakso', 'Opor Ayam'],
      differentiators: 'Opaque white coconut milk broth distinguishes soto betawi from soto ayam (clear yellow turmeric broth); contains beef and offal rather than chicken; emping crackers (not kerupuk) on the side.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -96 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 120 },
        ],
      },
    ],
  },

  'prawn-noodle-soup': {
    id: 'prawn-noodle-soup',
    name: 'Prawn Noodle Soup',
    nameLocal: '虾面',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍜',
    color: '#EA580C',
    bgColor: '#FFEDD5',
    description: 'A deeply flavoured orange-red broth made by simmering prawn heads and pork ribs, served with yellow noodles or bee hoon, whole prawns, kangkong, pork ribs, and fried shallots.',
    baseCalories: 450,
    calorieRange: { min: 320, max: 620 },
    macros: { protein: 28, carbs: 48, fat: 12, fiber: 3 },
    tags: ['Noodles', 'Prawn', 'Soup', 'Classic'],
    visual_detection: {
      protein: 'whole prawns (shell-on, pink-orange when cooked), pork rib segments',
      starch: 'yellow egg noodles and/or thin white bee hoon (rice vermicelli)',
      sauce: 'deep orange-red prawn broth — rich in colour from prawn shell stock, clear but intensely orange',
      sides: 'kangkong (water spinach) blanched green, fried shallots on top, sambal chilli on side',
      plating: 'large deep bowl with both noodle types, broth, prawns and ribs visible on top',
      key_identifiers: [
        'distinctive deep orange-red clear prawn broth',
        'whole prawns with shells visible in bowl',
        'pork rib bones visible',
        'kangkong (water spinach) blanched in bowl',
        'fried shallots on surface',
      ],
      common_lookalikes: ['Hokkien Mee', 'Mee Siam', 'Mee Bandung'],
      differentiators: 'Deep clear orange-red prawn broth (not thick or pink-tangy); whole prawns and pork ribs together in same bowl; kangkong is a defining garnish.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -90 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 113 },
        ],
      },
    ],
  },

  'yong-tau-foo': {
    id: 'yong-tau-foo',
    name: 'Yong Tau Foo',
    nameLocal: '酿豆腐',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍲',
    color: '#D97706',
    bgColor: '#FEF3C7',
    description: 'A customisable dish of tofu, vegetables, and fish cake varieties stuffed with fish paste, served in a clear soup or dry with a sweet sauce.',
    baseCalories: 280,
    calorieRange: { min: 180, max: 420 },
    macros: { protein: 18, carbs: 28, fat: 8, fiber: 4 },
    tags: ['Snack', 'Tofu', 'Light', 'Customisable'],
    visual_detection: {
      protein: 'fish paste stuffed into tofu, bitter gourd, eggplant, okra, fishballs',
      starch: 'bee hoon or noodles on the side; tofu as main item',
      sauce: 'clear light soup broth, or sweet chilli sauce for dry version',
      sides: 'assorted items: bitter gourd rings, eggplant halves, tofu varieties, fishballs, tau pok',
      plating: 'bowl with clear broth containing 5–8 assorted stuffed items, or dry bowl with sauce',
      key_identifiers: [
        'assorted items of different shapes and colours in one bowl',
        'fish paste visible in the cut side of vegetables and tofu',
        'clear light broth (not dark or creamy)',
        'variety of colours: green bitter gourd, purple eggplant, white tofu, orange fishballs',
        'customisable selection of items',
      ],
      common_lookalikes: ['Fishball Noodles', 'Laksa with tofu', 'Ban Mian'],
      differentiators: 'Distinguished by the wide variety of individually chosen stuffed items (not just noodles and toppings); the stuffed fish paste inside each item is the key feature.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -56 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 70 },
        ],
      },
    ],
  },

  'braised-duck-noodles': {
    id: 'braised-duck-noodles',
    name: 'Braised Duck Noodles',
    nameLocal: '卤鸭面',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍜',
    color: '#EA580C',
    bgColor: '#FFEDD5',
    description: 'Flat kway teow noodles or bee hoon served with sliced braised duck in a fragrant dark herbal soy broth, accompanied by a soy-braised hard-boiled egg and tau pok.',
    baseCalories: 520,
    calorieRange: { min: 380, max: 700 },
    macros: { protein: 30, carbs: 56, fat: 18, fiber: 2 },
    tags: ['Noodles', 'Duck', 'Braised', 'Herbal'],
    visual_detection: {
      protein: 'sliced braised duck — dark brown, moist, skin-on slices',
      starch: 'flat rice kway teow noodles or thin bee hoon',
      sauce: 'dark herbal soy broth — dark brown, aromatic from five spice and soy, semi-clear',
      sides: 'hard-boiled egg stained dark brown from braising, tau pok pieces, sliced cucumber',
      plating: 'bowl or plate with noodles, duck slices arranged on top, dark egg and tau pok alongside, broth poured over',
      key_identifiers: [
        'dark brown braised duck slices with visible skin',
        'flat kway teow or bee hoon noodles',
        'dark herbal soy broth (five spice aroma)',
        'dark braised egg',
        'tau pok pieces present',
      ],
      common_lookalikes: ['Duck Rice', 'Chicken Rice', 'Kway Chap'],
      differentiators: 'Braised duck noodles has noodles as the base (not rice like duck rice); broth is present (unlike duck rice which is dry with sauce); duck slices are the main protein over noodles.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -104 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 130 },
        ],
      },
    ],
  },

  'lor-mee': {
    id: 'lor-mee',
    name: 'Lor Mee',
    nameLocal: '卤面',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍜',
    color: '#EA580C',
    bgColor: '#FFEDD5',
    description: 'Flat yellow noodles smothered in a very thick, dark, starchy braising gravy (lor), topped with braised pork slices, fish cake, hard-boiled egg, and fried shallots, served with vinegar and chilli on the side.',
    baseCalories: 560,
    calorieRange: { min: 400, max: 760 },
    macros: { protein: 26, carbs: 72, fat: 16, fiber: 2 },
    tags: ['Noodles', 'Braised', 'Thick Gravy', 'Hokkien'],
    visual_detection: {
      protein: 'sliced braised pork belly, fish cake slices, hard-boiled egg half',
      starch: 'flat yellow noodles (broader and flatter than regular yellow mee)',
      sauce: 'very thick dark starchy gravy — glossy, gloopy, almost gel-like, dark brown colour from soy and starch thickener',
      sides: 'fried shallots, vinegar and chopped chilli in small dish on side, spring onion',
      plating: 'deep bowl or plate with noodles nearly buried under thick dark gravy, toppings arranged on top',
      key_identifiers: [
        'extremely thick gloopy dark starchy gravy coating noodles',
        'flat yellow noodles',
        'braised pork slices visible on top',
        'vinegar served as condiment on the side (unique to lor mee)',
        'fish cake slices present',
      ],
      common_lookalikes: ['Mee Rebus', 'Kway Chap'],
      differentiators: 'Very thick starchy gel-like dark gravy (thicker than mee rebus); flat yellow noodles; vinegar is the signature condiment served alongside — no other noodle dish comes with vinegar.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -112 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 140 },
        ],
      },
    ],
  },

  'kway-chap': {
    id: 'kway-chap',
    name: 'Kway Chap',
    nameLocal: '粿汁',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍲',
    color: '#0891B2',
    bgColor: '#CFFAFE',
    description: 'Broad flat rice noodle sheets served in a dark herbal soy broth, accompanied by a full spread of braised pork offal, pork belly, tofu, and dark soy-braised hard-boiled egg.',
    baseCalories: 520,
    calorieRange: { min: 380, max: 720 },
    macros: { protein: 32, carbs: 46, fat: 20, fiber: 2 },
    tags: ['Soup', 'Offal', 'Braised', 'Teochew'],
    visual_detection: {
      protein: 'braised pork belly slices, pig intestines, pig ear pieces — all dark brown from soy braising',
      starch: 'broad flat wide rice noodle sheets (kway) in dark broth — wide and flat, different from kway teow',
      sauce: 'dark herbal soy broth — very dark, aromatic with five spice, separate from braising sauce',
      sides: 'dark braised egg, tau pok, braised tofu',
      plating: 'flat wide noodle sheets in dark broth in a bowl, braised items served separately or alongside',
      key_identifiers: [
        'broad flat wide rice noodle sheets (not strips)',
        'very dark braised offal — intestines, ear, pork belly all dark brown',
        'dark herbal soy broth',
        'dark braised egg',
        'offal (intestines and ear) is the signature protein',
      ],
      common_lookalikes: ['Braised Duck Noodles', 'Lor Mee', 'Duck Kway Teow'],
      differentiators: 'Broad flat noodle sheets (not strips or yellow noodles); offal is the defining protein; broth and braising sauce are presented separately; more Teochew heritage than Hokkien.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -104 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 130 },
        ],
      },
    ],
  },

  'claypot-rice': {
    id: 'claypot-rice',
    name: 'Claypot Rice',
    nameLocal: '瓦煲饭',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍚',
    color: '#16A34A',
    bgColor: '#DCFCE7',
    description: 'Rice cooked directly in a clay pot over charcoal with Chinese sausage, dark soy-braised chicken, and salted fish, developing a crispy golden crust at the bottom.',
    baseCalories: 620,
    calorieRange: { min: 460, max: 850 },
    macros: { protein: 28, carbs: 78, fat: 20, fiber: 2 },
    tags: ['Malay', 'Rice', 'Claypot', 'Crispy'],
    visual_detection: {
      protein: 'sliced Chinese sausage (lap cheong) reddish-brown, dark chicken pieces, small pieces of salted fish',
      starch: 'white rice with crispy brown rice crust visible at edges of clay pot',
      sauce: 'dark soy sauce drizzled over, dark and glossy',
      sides: 'sliced spring onion, sometimes bok choy',
      plating: 'served in the clay pot itself — distinctive dark earthen clay vessel with contents visible from top',
      key_identifiers: [
        'distinctive dark clay pot serving vessel',
        'crispy rice crust visible at edges of pot',
        'Chinese sausage (lap cheong) slices visible on surface',
        'dark soy drizzle on top',
        'served directly in cooking vessel',
      ],
      common_lookalikes: ['Chicken Rice', 'Nasi Goreng', 'Stone Bowl Bibimbap'],
      differentiators: 'Distinctive clay pot vessel is unmistakable; crispy rice crust at edges; Chinese sausage is a defining ingredient; always served in the cooking vessel.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -124 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 155 },
        ],
      },
    ],
  },

  'oyster-omelette': {
    id: 'oyster-omelette',
    name: 'Oyster Omelette',
    nameLocal: '蚝煎 / Or Luak',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍳',
    color: '#D97706',
    bgColor: '#FEF3C7',
    description: 'A crispy-edged starchy egg omelette pan-fried with fresh oysters, made with tapioca starch for a chewy-crisp texture, served with a tangy chilli sauce.',
    baseCalories: 420,
    calorieRange: { min: 300, max: 580 },
    macros: { protein: 18, carbs: 38, fat: 22, fiber: 1 },
    tags: ['Snack', 'Seafood', 'Fried', 'Egg'],
    visual_detection: {
      protein: 'fresh oysters — plump, grey-brown, embedded in omelette',
      starch: 'white tapioca starch creates pale chewy sections within the omelette',
      sauce: 'tangy orange-red chilli sauce on the side',
      sides: 'spring onion and coriander garnish on top',
      plating: 'flat pan-fried omelette served on a plate, irregularly shaped, crispy charred edges, chilli sauce on side',
      key_identifiers: [
        'crispy charred edges on omelette',
        'visible white starchy sections (tapioca starch) within egg',
        'plump oysters embedded and visible',
        'irregular non-circular shape from wok frying',
        'tangy red chilli sauce always on the side',
      ],
      common_lookalikes: ['Egg Omelette', 'Chye Tow Kway (Carrot Cake)', 'Korean Pajeon'],
      differentiators: 'White starchy sections from tapioca starch mixed into egg is unique to or luak; oysters are always visible; crispy charred edges from high-heat wok cooking.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -84 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 105 },
        ],
      },
    ],
  },

  'muah-chee': {
    id: 'muah-chee',
    name: 'Muah Chee',
    nameLocal: '麻糍',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍡',
    color: '#D97706',
    bgColor: '#FEF3C7',
    description: 'Soft and chewy glutinous rice dough cut into bite-sized pieces and tossed in a generous coating of crushed peanuts mixed with sugar.',
    baseCalories: 280,
    calorieRange: { min: 200, max: 400 },
    macros: { protein: 6, carbs: 46, fat: 8, fiber: 2 },
    tags: ['Snack', 'Glutinous', 'Peanut', 'Sweet'],
    visual_detection: {
      protein: 'none',
      starch: 'soft pale white glutinous rice dough pieces, irregular bite-sized chunks',
      sauce: 'none',
      sides: 'none',
      plating: 'pieces served in a paper bag, box, or plate, heavily coated in tan/golden crushed peanut and sugar mixture',
      key_identifiers: [
        'pale white soft glutinous dough pieces',
        'completely coated in golden crushed peanut and sugar',
        'irregular bite-sized pieces (not uniform balls)',
        'no sauce or broth',
        'sold as street snack in small portions',
      ],
      common_lookalikes: ['Ondeh Ondeh', 'Tang Yuan', 'Mochi'],
      differentiators: 'Muah chee pieces are irregularly cut (not round balls like tang yuan), and are completely coated in crushed peanut — no liquid, no filling inside, no sugar syrup.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -56 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 70 },
        ],
      },
    ],
  },

  'tang-yuan': {
    id: 'tang-yuan',
    name: 'Tang Yuan',
    nameLocal: '汤圆',
    origin: 'China',
    flag: '🇨🇳',
    emoji: '🟢',
    color: '#EC4899',
    bgColor: '#FCE7F3',
    description: 'Round glutinous rice balls — plain white or coloured pink and green — served in a clear ginger syrup or sesame soup, traditionally eaten during the Lantern Festival and winter solstice.',
    baseCalories: 220,
    calorieRange: { min: 140, max: 340 },
    macros: { protein: 3, carbs: 44, fat: 4, fiber: 1 },
    tags: ['Dessert', 'Glutinous', 'Sweet Soup', 'Festive'],
    visual_detection: {
      protein: 'none',
      starch: 'round glutinous rice balls — white, pink, or green coloured spheres',
      sauce: 'clear pale yellow ginger syrup, or thin white sesame/peanut soup',
      sides: 'none',
      plating: 'small bowl with 4–8 round balls floating in clear or light-coloured sweet soup',
      key_identifiers: [
        'perfectly round smooth glutinous rice balls',
        'mix of white and coloured (pink/green) balls in same bowl',
        'clear or lightly tinted sweet ginger syrup',
        'balls float in the soup',
        'small dessert portion in a bowl',
      ],
      common_lookalikes: ['Onde Onde', 'Muah Chee', 'Tong Sui'],
      differentiators: 'Tang yuan are perfectly round smooth balls served in a liquid sweet soup — unlike muah chee (no soup, coated in peanut) or onde onde (rolled in coconut, no soup).',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -44 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 55 },
        ],
      },
    ],
  },
