  'grilled-chicken-set': {
    id: 'grilled-chicken-set',
    name: 'Grilled Chicken Set',
    nameLocal: '',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍗',
    color: '#B45309',
    bgColor: '#FEF3C7',
    description: 'Char-grilled skin-on chicken thigh served with thick wedge fries, garden salad, and sweet chilli dipping sauce — a kopitiam Western staple with no gravy.',
    baseCalories: 680,
    calorieRange: { min: 480, max: 920 },
    macros: { protein: 42, carbs: 52, fat: 22, fiber: 4 },
    tags: ['Western', 'Grilled', 'Chicken', 'Kopitiam'],
    visual_detection: {
      protein: 'grilled chicken thigh, skin-on, visible char marks, no batter or breading',
      starch: 'thick-cut wedge fries, skin-on potato wedges',
      sauce: 'sweet chilli sauce in a small cup on the side, no gravy on plate',
      sides: 'garden salad with lettuce, broccoli florets, cherry tomatoes, and cucumber slices',
      plating: 'oval or rectangular plate, fries alongside chicken, salad in corner, sauce cup on side',
      key_identifiers: [
        'Char marks on chicken from grill grates — not fried',
        'Thick wedge-cut fries, not crinkle-cut or shoestring',
        'Garden salad with distinct raw vegetables (broccoli, cherry tomato)',
        'Sweet chilli sauce in small cup — no brown or mushroom gravy anywhere',
        'Skin-on chicken thigh, not a whole chop or crumbed cutlet',
      ],
      common_lookalikes: ['Chicken Chop', 'Fish and Chips', 'Pork Chop'],
      differentiators: 'Grilled char marks (not pan-fried), wedge fries (not crinkle-cut or shoestring), raw garden salad (not mixed cooked veg), absolutely no gravy on plate — only sweet chilli dipping cup.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -136 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 170 },
        ],
      },
    ],
  },

  'hainanese-beef-steak': {
    id: 'hainanese-beef-steak',
    name: 'Hainanese Beef Steak',
    nameLocal: '',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🥩',
    color: '#B45309',
    bgColor: '#FEF3C7',
    description: 'Thin-cut pan-fried beef steak smothered in a tangy Worcestershire-tomato sauce, topped with a fried egg and served with shoestring fries and garden peas — a Hainanese kopitiam Western classic.',
    baseCalories: 820,
    calorieRange: { min: 600, max: 1080 },
    macros: { protein: 48, carbs: 58, fat: 34, fiber: 4 },
    tags: ['Western', 'Beef', 'Kopitiam', 'Hainanese'],
    visual_detection: {
      protein: 'thin-cut pan-fried beef steak, not thick-cut, no char grill marks',
      starch: 'shoestring fries, thin and straight-cut',
      sauce: 'dark reddish-brown Worcestershire-tomato sauce ladled generously over the steak',
      sides: 'green garden peas on the side of the plate',
      plating: 'oval or round plate, steak centre-stage with sauce poured over, fried egg on top of steak, fries and peas flanking',
      key_identifiers: [
        'Fried egg placed directly on top of the steak',
        'Dark reddish-brown Worcestershire-tomato sauce covering the meat',
        'Thin-cut beef (not thick steakhouse cut)',
        'Shoestring fries (thin, not wedge)',
        'Green peas as side (not mixed veg or salad)',
      ],
      common_lookalikes: ['Pork Chop', 'Lamb Chop', 'Chicken Chop'],
      differentiators: 'Fried egg on top of steak is the hallmark; reddish-brown tangy sauce (not pepper or mushroom cream); thin beef cut; shoestring fries; green peas only as side.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -164 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 205 },
        ],
      },
    ],
  },

  'lamb-chop-kopitiam': {
    id: 'lamb-chop-kopitiam',
    name: 'Lamb Chop',
    nameLocal: '',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🥩',
    color: '#B45309',
    bgColor: '#FEF3C7',
    description: 'Two pan-fried lamb chops served with black pepper sauce, shoestring fries, and mixed vegetables — a hearty kopitiam Western dish.',
    baseCalories: 900,
    calorieRange: { min: 650, max: 1150 },
    macros: { protein: 52, carbs: 55, fat: 42, fiber: 4 },
    tags: ['Western', 'Lamb', 'Kopitiam', 'Black Pepper'],
    visual_detection: {
      protein: 'two pan-fried lamb chops with visible bone handle, slight browning, no breading',
      starch: 'shoestring fries, thin and straight-cut',
      sauce: 'dark brown black pepper sauce, thick and glossy, poured over or alongside chops',
      sides: 'mixed vegetables (corn kernels, diced carrots, green peas)',
      plating: 'large oval plate, two bone-in lamb chops as centrepiece, fries and mixed veg on sides',
      key_identifiers: [
        'Two bone-in lamb chops — distinctive rib bone handles',
        'Dark black pepper sauce (not mushroom cream or tomato)',
        'Pan-fried surface — no grill marks',
        'Shoestring fries (not wedge)',
        'Mixed corn/carrot/pea vegetables',
      ],
      common_lookalikes: ['Pork Chop', 'Chicken Chop', 'Hainanese Beef Steak'],
      differentiators: 'Two rib-bone chops identify lamb; darker, spicier black pepper sauce distinguishes from pork chop; no fried egg on top unlike beef steak.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -180 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 225 },
        ],
      },
    ],
  },

  'chicken-cutlet-rice': {
    id: 'chicken-cutlet-rice',
    name: 'Chicken Cutlet Rice',
    nameLocal: '',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍽️',
    color: '#B45309',
    bgColor: '#FEF3C7',
    description: 'Golden fried breaded chicken cutlet served over steamed white rice with black pepper or mushroom sauce — no fries, a rice-based kopitiam Western plate.',
    baseCalories: 620,
    calorieRange: { min: 440, max: 820 },
    macros: { protein: 36, carbs: 68, fat: 18, fiber: 2 },
    tags: ['Western', 'Chicken', 'Fried', 'Rice'],
    visual_detection: {
      protein: 'breaded fried chicken cutlet, flat and wide, golden-brown crumb coating',
      starch: 'steamed white jasmine rice, mounded or scooped alongside or under cutlet',
      sauce: 'black pepper sauce or creamy mushroom sauce poured over the cutlet',
      sides: 'minimal — sometimes a small side salad or coleslaw',
      plating: 'round or oval plate, rice base with cutlet on top or beside, sauce ladled over',
      key_identifiers: [
        'Breaded flat chicken cutlet (not whole thigh, not grilled)',
        'Served with rice — not fries',
        'Black pepper or mushroom sauce (not sweet chilli)',
        'No wedge fries or shoestring fries on plate',
        'Flat, wide cutlet shape distinct from whole thigh',
      ],
      common_lookalikes: ['Chicken Rice', 'Chicken Chop', 'Mushroom Chicken Chop'],
      differentiators: 'Rice base instead of fries is the primary differentiator from chicken chop; breaded crumb coating distinguishes from plain steamed chicken rice; sauce colour (pepper/mushroom) not the sweet chilli of chicken rice.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -124 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 155 },
        ],
      },
    ],
  },

  'mushroom-chicken-chop': {
    id: 'mushroom-chicken-chop',
    name: 'Mushroom Chicken Chop',
    nameLocal: '',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍽️',
    color: '#B45309',
    bgColor: '#FEF3C7',
    description: 'Pan-fried whole chicken chop smothered in a creamy mushroom sauce, served with crinkle-cut fries and mixed vegetables.',
    baseCalories: 760,
    calorieRange: { min: 540, max: 1000 },
    macros: { protein: 44, carbs: 58, fat: 30, fiber: 4 },
    tags: ['Western', 'Chicken', 'Mushroom', 'Kopitiam'],
    visual_detection: {
      protein: 'pan-fried whole chicken chop (thigh and drumstick or large breast piece), no batter, lightly browned skin',
      starch: 'crinkle-cut fries — wavy ridged edges distinguish from straight shoestring',
      sauce: 'pale creamy beige mushroom sauce with visible mushroom slices poured generously over chicken',
      sides: 'mixed vegetables — corn kernels, diced carrots, green peas',
      plating: 'large oval or round plate, chicken centre, crinkle fries on one side, mixed veg on other, sauce covering chicken',
      key_identifiers: [
        'Creamy pale mushroom sauce with visible mushroom pieces — not dark pepper or tomato',
        'Crinkle-cut wavy fries (not shoestring or wedge)',
        'Whole bone-in chicken chop (not cutlet, not thigh alone)',
        'Mixed corn/carrot/pea veg alongside',
        'No fried egg, no gravy colour darker than cream',
      ],
      common_lookalikes: ['Chicken Chop (black pepper)', 'Pork Chop', 'Chicken Cutlet Rice'],
      differentiators: 'Creamy pale mushroom sauce is the key tell; crinkle-cut fries distinguish from wedge (grilled set) or shoestring (beef steak/lamb); no rice on plate unlike chicken cutlet rice.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -152 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 190 },
        ],
      },
    ],
  },

  'thosai-plain': {
    id: 'thosai-plain',
    name: 'Thosai (Plain)',
    nameLocal: 'தோசை',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🫓',
    color: '#DC2626',
    bgColor: '#FEE2E2',
    description: 'Thin, large crispy crepe made from fermented rice and lentil batter, served with sambar lentil soup and coconut chutney.',
    baseCalories: 150,
    calorieRange: { min: 100, max: 220 },
    macros: { protein: 4, carbs: 28, fat: 3, fiber: 2 },
    tags: ['Indian', 'Vegetarian', 'Crepe', 'Fermented'],
    visual_detection: {
      protein: 'none — plain fermented batter only',
      starch: 'thin fermented rice-lentil crepe, large diameter (30–35 cm), lacy holes, pale golden-brown',
      sauce: 'sambar (thin reddish-brown lentil soup) and white coconut chutney in small cups on side',
      sides: 'sambar cup and coconut chutney cup',
      plating: 'flat plate or banana leaf, crepe served flat or folded/rolled, two condiment cups alongside',
      key_identifiers: [
        'Very thin, almost translucent crepe with lacy holes when held to light',
        'Large diameter (plate-sized), pale golden colour',
        'No filling visible — completely plain inside',
        'Served with two cups: reddish sambar and white coconut chutney',
        'Slight crisp at edges, softer at centre',
      ],
      common_lookalikes: ['Thosai Egg', 'Murtabak', 'Roti Canai'],
      differentiators: 'Thinner and more translucent than roti canai; no egg visible unlike thosai egg; no thick stuffing unlike murtabak; lacy texture from fermentation.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -30 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 38 },
        ],
      },
    ],
  },

  'thosai-egg': {
    id: 'thosai-egg',
    name: 'Thosai (Egg)',
    nameLocal: 'முட்டை தோசை',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🫓',
    color: '#DC2626',
    bgColor: '#FEE2E2',
    description: 'Fermented rice and lentil crepe with an egg broken and cooked directly on the batter, creating a thicker egg-layered centre, served with sambar and coconut chutney.',
    baseCalories: 230,
    calorieRange: { min: 160, max: 320 },
    macros: { protein: 9, carbs: 28, fat: 8, fiber: 2 },
    tags: ['Indian', 'Egg', 'Crepe', 'Fermented'],
    visual_detection: {
      protein: 'one egg cracked and spread across the centre of the crepe, cooked into the batter',
      starch: 'fermented rice-lentil crepe base, same diameter as plain thosai',
      sauce: 'sambar and coconut chutney in cups on side',
      sides: 'sambar cup and coconut chutney cup',
      plating: 'flat plate, crepe folded or flat showing egg layer at centre, thicker in middle than at edges',
      key_identifiers: [
        'Visible egg layer in the centre — yellowy-white cooked egg spread across the batter',
        'Centre is noticeably thicker than the thin crispy edges',
        'Same large diameter as plain thosai',
        'Edges still have the characteristic lacy crisp',
        'Two condiment cups (sambar and chutney) alongside',
      ],
      common_lookalikes: ['Thosai Plain', 'Murtabak', 'Egg Roti Canai'],
      differentiators: 'Egg visible and spread across the crepe surface distinguishes from plain thosai; thinner and no stuffing unlike murtabak; fermented rice-lentil batter (not flaky wheat) distinguishes from egg roti canai.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -46 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 58 },
        ],
      },
    ],
  },

  'murtabak-chicken': {
    id: 'murtabak-chicken',
    name: 'Murtabak (Chicken)',
    nameLocal: 'مرتبك',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🫓',
    color: '#DC2626',
    bgColor: '#FEE2E2',
    description: 'Thick pan-fried stuffed pancake filled with spiced minced chicken and egg, served with a thin curry sauce and pickled onions.',
    baseCalories: 580,
    calorieRange: { min: 400, max: 760 },
    macros: { protein: 28, carbs: 58, fat: 22, fiber: 3 },
    tags: ['Indian', 'Stuffed', 'Chicken', 'Pan-fried'],
    visual_detection: {
      protein: 'spiced minced chicken mixed with egg, visible at cut edges or filling exposed at corners',
      starch: 'thick layered wheat pancake dough, golden-brown pan-fried exterior, cut into squares or rectangles',
      sauce: 'thin yellow-orange curry sauce in a small bowl on side; pickled onion slices in another small cup',
      sides: 'pickled white onion rings in vinegar',
      plating: 'flat plate with murtabak cut into rectangular pieces, curry sauce bowl and pickled onion cup alongside',
      key_identifiers: [
        'Thick square or rectangular pan-fried pancake — much thicker than thosai',
        'Golden-brown oily exterior from pan-frying in ghee',
        'Minced filling visible at cut edges (chicken pieces mixed with egg)',
        'Served with yellow curry dipping sauce (not coconut chutney)',
        'Pickled white onion rings as garnish',
      ],
      common_lookalikes: ['Murtabak Mutton', 'Thosai', 'Roti Canai'],
      differentiators: 'Much thicker than thosai or roti canai; visible filling at edges; rectangular shape; curry dipping sauce not coconut chutney; chicken filling (lighter colour) vs mutton (darker).',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -116 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 145 },
        ],
      },
    ],
  },

  'murtabak-mutton': {
    id: 'murtabak-mutton',
    name: 'Murtabak (Mutton)',
    nameLocal: 'مرتبك',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🫓',
    color: '#DC2626',
    bgColor: '#FEE2E2',
    description: 'Thick pan-fried stuffed pancake filled with spiced minced mutton and egg, served with curry sauce and pickled onions — richer and more aromatic than the chicken version.',
    baseCalories: 620,
    calorieRange: { min: 430, max: 820 },
    macros: { protein: 30, carbs: 58, fat: 26, fiber: 3 },
    tags: ['Indian', 'Stuffed', 'Mutton', 'Pan-fried'],
    visual_detection: {
      protein: 'spiced minced mutton with egg, darker brown filling visible at cut edges',
      starch: 'thick layered wheat pancake, golden-brown pan-fried exterior, cut into squares',
      sauce: 'thin yellow-orange curry sauce in small bowl; pickled onion slices',
      sides: 'pickled white onion rings in vinegar',
      plating: 'flat plate with rectangular murtabak pieces, curry sauce bowl and pickled onion cup alongside',
      key_identifiers: [
        'Thick golden-brown pan-fried pancake — same shape as chicken murtabak',
        'Darker brownish filling at edges (mutton is darker than chicken)',
        'Stronger aromatic spice smell from mutton filling',
        'Curry dipping sauce and pickled onion on side',
        'Oily glistening exterior from ghee frying',
      ],
      common_lookalikes: ['Murtabak Chicken', 'Thosai', 'Roti Canai'],
      differentiators: 'Darker filling colour distinguishes mutton from chicken murtabak; thicker than thosai or roti canai; visible stuffing at edges; rectangular shape and curry dipping sauce.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -124 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 155 },
        ],
      },
    ],
  },

  'briyani-chicken': {
    id: 'briyani-chicken',
    name: 'Chicken Briyani',
    nameLocal: 'Nasi Briyani Ayam',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍛',
    color: '#DC2626',
    bgColor: '#FEE2E2',
    description: 'Fragrant saffron and turmeric-tinted long-grain basmati rice mounded on a plate with bone-in chicken curry pieces, cooling raita, and pickled onion.',
    baseCalories: 680,
    calorieRange: { min: 480, max: 920 },
    macros: { protein: 36, carbs: 82, fat: 18, fiber: 3 },
    tags: ['Indian', 'Rice', 'Chicken', 'Aromatic'],
    visual_detection: {
      protein: 'bone-in chicken curry pieces — drumstick or thigh, coated in orange-red curry masala',
      starch: 'long-grain basmati rice with golden yellow saffron/turmeric tint, mounded, with visible fried onion and whole spices (cardamom, clove, bay leaf)',
      sauce: 'orange-red chicken curry sauce around chicken pieces; thin white raita yoghurt',
      sides: 'small cup of white raita (yoghurt dip) and pickled onion slices',
      plating: 'large plate or banana leaf — tall mound of yellow basmati rice with chicken on the side, raita cup alongside',
      key_identifiers: [
        'Yellow-gold long-grain basmati rice (not short-grain white rice)',
        'Whole spices visible in rice (cardamom pods, cloves, bay leaves)',
        'Fried golden onion strands mixed through the rice',
        'Bone-in chicken curry pieces alongside rice',
        'White raita cup and pickled onion as condiments',
      ],
      common_lookalikes: ['Briyani Mutton', 'Nasi Padang', 'Curry Chicken with Rice'],
      differentiators: 'Long-grain yellow basmati rice with whole spices identifies briyani; chicken pieces (lighter meat, smaller bone) vs mutton (darker meat, lamb bone); raita and pickled onion are signature accompaniments.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -136 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 170 },
        ],
      },
    ],
  },

  'briyani-mutton': {
    id: 'briyani-mutton',
    name: 'Mutton Briyani',
    nameLocal: 'Nasi Briyani Kambing',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍛',
    color: '#DC2626',
    bgColor: '#FEE2E2',
    description: 'Fragrant saffron basmati rice served with braised bone-in mutton curry pieces that are deep-red and fall-off-the-bone tender, accompanied by cooling raita.',
    baseCalories: 750,
    calorieRange: { min: 530, max: 1000 },
    macros: { protein: 40, carbs: 82, fat: 24, fiber: 3 },
    tags: ['Indian', 'Rice', 'Mutton', 'Aromatic'],
    visual_detection: {
      protein: 'bone-in mutton pieces — deep dark-red braised curry colour, larger irregular lamb bones',
      starch: 'long-grain basmati rice with deep saffron-yellow tint, mounded, with fried onion and whole spices',
      sauce: 'dark reddish-brown mutton curry sauce; white raita',
      sides: 'raita and pickled onion',
      plating: 'large plate or banana leaf, tall rice mound, dark mutton pieces alongside, raita cup',
      key_identifiers: [
        'Darker, richer curry colour on mutton vs chicken briyani',
        'Larger irregular lamb/mutton bones',
        'Deep saffron-gold rice with whole spices (cardamom, star anise)',
        'Richer, more aromatic curry sauce than chicken version',
        'White raita and pickled onion accompaniments',
      ],
      common_lookalikes: ['Briyani Chicken', 'Nasi Padang', 'Fish Head Curry with Rice'],
      differentiators: 'Darker richer mutton curry distinguishes from chicken briyani; yellow long-grain basmati (not short-grain) identifies as briyani vs nasi padang; large lamb bones confirm mutton.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -150 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 188 },
        ],
      },
    ],
  },

  'fish-head-curry': {
    id: 'fish-head-curry',
    name: 'Fish Head Curry',
    nameLocal: '',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🐟',
    color: '#DC2626',
    bgColor: '#FEE2E2',
    description: 'A large red snapper fish head half-submerged in a rich, spiced coconut milk curry with okra and brinjal, served in a large claypot or on a plate.',
    baseCalories: 520,
    calorieRange: { min: 360, max: 720 },
    macros: { protein: 42, carbs: 18, fat: 28, fiber: 5 },
    tags: ['Indian', 'Seafood', 'Curry', 'Coconut'],
    visual_detection: {
      protein: 'large fish head (red snapper), half-submerged in curry, with visible eye socket and cheek meat',
      starch: 'none — typically served alongside steamed rice separately',
      sauce: 'rich deep-red to orange-red coconut milk curry, thick and aromatic',
      sides: 'lady\'s fingers (okra) and brinjal (eggplant) visible in the curry',
      plating: 'large claypot or deep serving plate — fish head is visually dominant, vegetables submerged around it',
      key_identifiers: [
        'Unmistakable large fish head dominating the pot or plate',
        'Visible eye socket and gills — unique identifier',
        'Rich red-orange coconut curry with whole chillies',
        'Okra (green star-shaped cross-section) and brinjal visible',
        'Claypot serving vessel or large deep plate',
      ],
      common_lookalikes: ['Curry Chicken', 'Fish Curry', 'Assam Fish'],
      differentiators: 'Whole fish head is unmistakable — eye socket and facial structure visible; richer thicker coconut curry than assam fish; larger serving vessel than standard curry chicken.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -104 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 130 },
        ],
      },
    ],
  },

  'curry-chicken': {
    id: 'curry-chicken',
    name: 'Curry Chicken',
    nameLocal: 'Kari Ayam',
    origin: 'Singapore',
    flag: '🇸🇬',
    emoji: '🍛',
    color: '#DC2626',
    bgColor: '#FEE2E2',
    description: 'Bone-in chicken pieces simmered in a rich yellow-orange coconut milk curry with potato chunks, served in a bowl or alongside rice.',
    baseCalories: 480,
    calorieRange: { min: 320, max: 680 },
    macros: { protein: 32, carbs: 24, fat: 28, fiber: 3 },
    tags: ['Indian', 'Curry', 'Chicken', 'Coconut'],
    visual_detection: {
      protein: 'bone-in chicken pieces (drumstick, thigh, wing) with yellow-orange curry coating',
      starch: 'potato chunks (medium-sized, yellow-white, softened in curry)',
      sauce: 'bright yellow to orange coconut milk curry — lighter in colour than fish head curry, rich and creamy',
      sides: 'sometimes served with bread, roti, or rice separately',
      plating: 'bowl or deep plate with chicken pieces and potato in curry sauce',
      key_identifiers: [
        'Bright yellow-orange curry colour from turmeric and coconut milk',
        'Soft potato chunks submerged in curry alongside chicken',
        'Bone-in chicken pieces with curry coating on skin',
        'Creamy, coconut-rich texture — not thin or broth-like',
        'No fish head or large vegetables like okra',
      ],
      common_lookalikes: ['Fish Head Curry', 'Briyani Chicken', 'Dal Curry'],
      differentiators: 'Bright yellow-orange colour and potato chunks are hallmarks; no fish head; lighter and creamier than fish head curry; potato distinguishes from briyani chicken which has no potato in curry.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -96 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 120 },
        ],
      },
    ],
  },

  'dal-curry': {
    id: 'dal-curry',
    name: 'Dal Curry',
    nameLocal: 'दाल',
    origin: 'India',
    flag: '🇮🇳',
    emoji: '🍲',
    color: '#DC2626',
    bgColor: '#FEE2E2',
    description: 'Slow-cooked yellow or orange lentil dal in a small bowl, finished with a tarka of fried onions and cumin, served alongside rice or flatbread.',
    baseCalories: 220,
    calorieRange: { min: 150, max: 320 },
    macros: { protein: 12, carbs: 30, fat: 6, fiber: 8 },
    tags: ['Indian', 'Vegetarian', 'Lentil', 'Vegan'],
    visual_detection: {
      protein: 'none — lentils are the protein source but no meat',
      starch: 'yellow/orange lentils (toor dal, masoor dal, or chana dal), soft and slightly textured',
      sauce: 'thick yellow to orange lentil broth, topped with tarka — fried onion rings and cumin seeds with a drizzle of red-orange oil',
      sides: 'served with rice or chapati/naan on the side',
      plating: 'small bowl or katori, tarka poured on top as garnish, served as accompaniment not main dish',
      key_identifiers: [
        'Thick yellow-orange lentil base — not a clear broth',
        'Tarka garnish on top: fried onion, cumin, sometimes dried red chilli',
        'Poured in small bowl — side dish size',
        'No meat pieces anywhere in dish',
        'Matte, slightly grainy texture from lentils',
      ],
      common_lookalikes: ['Curry Chicken', 'Sambar', 'Dhal Soup'],
      differentiators: 'Thick matte yellow texture from lentils (not a thin soup like sambar); no meat; tarka garnish on top is distinctive; served as small side bowl not main curry.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -44 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 55 },
        ],
      },
    ],
  },

  'tandoori-chicken': {
    id: 'tandoori-chicken',
    name: 'Tandoori Chicken',
    nameLocal: 'तंदूरी चिकन',
    origin: 'India',
    flag: '🇮🇳',
    emoji: '🍗',
    color: '#DC2626',
    bgColor: '#FEE2E2',
    description: 'Marinated chicken pieces with deep-red tandoori spice and yoghurt coating, charred in a clay tandoor oven, served on a metal plate with lemon wedge and mint chutney.',
    baseCalories: 350,
    calorieRange: { min: 240, max: 500 },
    macros: { protein: 42, carbs: 6, fat: 16, fiber: 1 },
    tags: ['Indian', 'Grilled', 'Chicken', 'Tandoor'],
    visual_detection: {
      protein: 'bone-in chicken pieces (leg quarter or half chicken) with deep red-orange tandoori spice marinade, visible char marks',
      starch: 'none on the plate — low-carb dish',
      sauce: 'mint chutney (bright green) in a small cup; no gravy',
      sides: 'lemon wedge, sliced white onion rings, fresh coriander sprig',
      plating: 'oval metal sizzler plate or round plate, chicken pieces arranged with lemon wedge and onion, mint chutney cup on side',
      key_identifiers: [
        'Deep brick-red to orange-red colour from tandoori marinade — very distinctive',
        'Char marks and slightly blackened edges from clay oven',
        'Bone-in pieces with no sauce or gravy on top',
        'Bright green mint chutney as accompaniment',
        'Lemon wedge and raw onion rings on plate',
      ],
      common_lookalikes: ['Grilled Chicken Set', 'BBQ Chicken', 'Chicken Tikka'],
      differentiators: 'Intense deep-red marinade colour is unmistakable; clay oven char marks different from grill char; no fries or salad on plate; mint chutney (not sweet chilli) as accompaniment.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -70 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 88 },
        ],
      },
    ],
  },

  'chapati': {
    id: 'chapati',
    name: 'Chapati',
    nameLocal: 'चपाती',
    origin: 'India',
    flag: '🇮🇳',
    emoji: '🫓',
    color: '#DC2626',
    bgColor: '#FEE2E2',
    description: 'Thin whole-wheat unleavened flatbread with soft, pliable texture and light charred spots, served alongside dal or curry for dipping and scooping.',
    baseCalories: 120,
    calorieRange: { min: 80, max: 160 },
    macros: { protein: 3, carbs: 22, fat: 3, fiber: 2 },
    tags: ['Indian', 'Bread', 'Vegetarian', 'Wholemeal'],
    visual_detection: {
      protein: 'none',
      starch: 'thin round whole-wheat flatbread, roughly 20–25 cm diameter, even thickness throughout',
      sauce: 'none on the bread itself; served alongside dal or curry',
      sides: 'dal, curry, or chutney for dipping',
      plating: 'flat plate or stacked in a covered basket; often folded in half or quarters',
      key_identifiers: [
        'Thin, uniformly round flatbread with whole-wheat brown colouring',
        'Light charred dark spots from tawa (griddle) heat',
        'Soft and pliable — bends without breaking',
        'No puffing or layering (distinguishes from naan or roti canai)',
        'Matte, dry surface — no butter or oil gloss unless buttered after cooking',
      ],
      common_lookalikes: ['Naan', 'Roti Canai', 'Thosai'],
      differentiators: 'Thinner and flatter than naan with no puffing; whole-wheat brown colour (not pale white of naan); no flaky layers unlike roti canai; smaller diameter and not crispy like thosai.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -24 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 30 },
        ],
      },
    ],
  },

  'naan': {
    id: 'naan',
    name: 'Naan',
    nameLocal: 'नान',
    origin: 'India',
    flag: '🇮🇳',
    emoji: '🫓',
    color: '#DC2626',
    bgColor: '#FEE2E2',
    description: 'Soft leavened tandoor-baked flatbread with puffy air pockets and charred spots, typically brushed with butter or garlic butter and served as a tear-and-share bread.',
    baseCalories: 260,
    calorieRange: { min: 180, max: 360 },
    macros: { protein: 7, carbs: 44, fat: 7, fiber: 2 },
    tags: ['Indian', 'Bread', 'Baked', 'Tandoor'],
    visual_detection: {
      protein: 'none',
      starch: 'leavened wheat flatbread, teardrop or oval shape, puffy with large air bubbles blistered on surface',
      sauce: 'butter or garlic butter brushed on surface, giving a glossy sheen',
      sides: 'curry, dal, or dipping sauce alongside',
      plating: 'flat plate or bread basket, often folded, glossy from butter brushing',
      key_identifiers: [
        'Teardrop or elongated oval shape — not round like chapati',
        'Puffy blistered surface with large and small air pockets',
        'Charred dark spots on top from tandoor heat',
        'Glossy butter-brushed surface',
        'Thick, soft, chewy texture — not thin or crispy',
      ],
      common_lookalikes: ['Chapati', 'Roti Canai', 'Garlic Bread'],
      differentiators: 'Puffy blistered surface with large air pockets is unique; teardrop shape (not round like chapati); thicker and softer than chapati; butter gloss on surface; no flaky layers unlike roti canai.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -52 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 65 },
        ],
      },
    ],
  },

  'lassi': {
    id: 'lassi',
    name: 'Lassi',
    nameLocal: 'ਲੱਸੀ',
    origin: 'India',
    flag: '🇮🇳',
    emoji: '🥛',
    color: '#2563EB',
    bgColor: '#DBEAFE',
    description: 'Tall chilled glass of thick blended yoghurt drink — pale yellow for mango lassi or creamy white for plain — sometimes topped with a swirl of cream.',
    baseCalories: 180,
    calorieRange: { min: 120, max: 280 },
    macros: { protein: 6, carbs: 28, fat: 4, fiber: 0 },
    tags: ['Drink', 'Yoghurt', 'Indian', 'Chilled'],
    visual_detection: {
      protein: 'none',
      starch: 'none',
      sauce: 'thick, smooth, opaque yoghurt-based liquid — pale yellow (mango) or white (plain)',
      sides: 'sometimes a pinch of cardamom powder or saffron on top',
      plating: 'tall glass (250–350 ml), thick smoothie-like consistency, sometimes a cream swirl on surface',
      key_identifiers: [
        'Tall glass filled with thick, opaque, smooth yoghurt drink',
        'Pale yellow colour (mango) or pure white (plain/salted)',
        'Thick consistency — not watery like juice',
        'Cream swirl or frothy top in some versions',
        'Served very cold with condensation on glass',
      ],
      common_lookalikes: ['Mango Juice', 'Smoothie', 'Teh Tarik'],
      differentiators: 'Thick opaque yoghurt consistency (not clear or translucent like juice); pale yellow or white colour; taller glass than teh tarik; no tea colour or froth pattern of teh tarik.',
    },
    questions: [
      {
        id: 'portion',
        question: 'How big was your portion?',
        subtitle: 'Portion size is the biggest calorie variable',
        type: 'single',
        options: [
          { id: 'small', label: 'Small', desc: 'Light / half portion', icon: '🤏', modifier: -36 },
          { id: 'regular', label: 'Regular', desc: 'Standard serving', icon: '👌', modifier: 0 },
          { id: 'large', label: 'Large', desc: 'Generous portion', icon: '👐', modifier: 45 },
        ],
      },
    ],
  },
